# Password login. Listen addresses are in 10-netmaker-only.conf.
AddressFamily inet
PasswordAuthentication yes
KbdInteractiveAuthentication yes
PermitRootLogin yes
PubkeyAuthentication yes
UsePAM yes
LogLevel VERBOSE
