[Interface]
PrivateKey = sH92SGw4Uaeh2V3559yZNIzdGbKYqvoYvLNpxxW5dUo=
Address = 10.0.0.3/32
DNS = 1.1.1.1

[Peer]
PublicKey = iLhke0pGcCln2RYk0R9Zd/gAPo06UcJw6wne6kcVfgQ=
AllowedIPs = 0.0.0.0/0
Endpoint = 148.113.204.83:51820
PersistentKeepalive = 25
