{
 "title": "Netmaker Metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodes_src",
    "query": {
     "query": "label_values(nm_connected, nm_peer_src)"
    }
   },
   {
    "name": "nodes_dst",
    "query": {
     "query": "label_values(nm_connected,nm_peer_dst)"
    }
   },
   {
    "name": "network",
    "label": "network",
    "query": {
     "query": "label_values(nm_connected,network)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Latency between network peers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nm_latency{nm_peer_src=\"$nodes_src\", nm_peer_dst=\"$nodes_dst\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Sent/Recieved",
   "type": "stat",
   "description": "Bytes exchanged between peers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nm_bytes_sent{nm_peer_src=\"$nodes_src\", nm_peer_dst=\"$nodes_dst\", network=\"$network\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nm_bytes_recv{nm_peer_src=\"$nodes_src\", nm_peer_dst=\"$nodes_dst\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection status",
   "type": "timeseries",
   "description": "0 - disconnected\n1 - connected",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nm_connected{nm_peer_src=\"$nodes_src\", nm_peer_dst=\"$nodes_dst\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Time/Active Time ",
   "type": "stat",
   "description": "Total time - since the node joined its peer in the network (mins)\n\nActive time - active connection time to its peer in the network (mins)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nm_total_up_time{nm_peer_src=\"$nodes_src\", nm_peer_dst=\"$nodes_dst\", network=\"$network\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nm_up_time{nm_peer_src=\"$nodes_src\", nm_peer_dst=\"$nodes_dst\", network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}