[Interface]
PrivateKey = YKUt2IvutXVgXdvZ1W9YrgKuLugNP/mpgGabLcyjt0U=
Address = 10.0.0.3/24
Table = off

[Peer]
PublicKey = 6mx4ycJeDMEDUknDY+sVlus1PQOEGG9/XrGFBuB1GFY=
Endpoint = 129.153.134.63:51821
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
