[Interface]
PrivateKey = gFCoBvwIyT06NnYk7XP7/V1O3StA4oFhS/BqqSXIokA=
Address = 10.0.0.3/24

[Peer]
PublicKey = iNqgBk7pBC/iXUmF+v4PNvvdAxjP5qWjxzMYYRE8+hw=
Endpoint = 148.113.204.83:51823
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
