// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendRequest {
    /// Groups episodes into task chains (threaded)
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
    /// JSON-encoded UIMessage\[\] (AI SDK shape)
    #[prost(bytes = "vec", tag = "2")]
    pub ui_messages: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, optional, tag = "3")]
    pub persona_id: ::core::option::Option<::prost::alloc::string::String>,
    /// zeroclaw-selected provider (OD-28)
    #[prost(string, tag = "4")]
    pub provider: ::prost::alloc::string::String,
    /// zeroclaw-selected model (OD-28)
    #[prost(string, tag = "5")]
    pub model: ::prost::alloc::string::String,
    /// Resume from last known cursor on reconnect
    #[prost(uint64, optional, tag = "6")]
    pub resume_cursor: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApproveRequest {
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
    /// The tool call to approve
    #[prost(string, tag = "2")]
    pub tool_call_id: ::prost::alloc::string::String,
    /// true = proceed, false = reject
    #[prost(bool, tag = "3")]
    pub approved: bool,
    /// Optional reason for rejection
    #[prost(string, optional, tag = "4")]
    pub operator_note: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelRequest {
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatFrame {
    /// Monotonically increasing; out-of-order = protocol error
    #[prost(uint64, tag = "1")]
    pub cursor: u64,
    #[prost(oneof = "chat_frame::Body", tags = "2, 3, 4, 5, 6")]
    pub body: ::core::option::Option<chat_frame::Body>,
}
/// Nested message and enum types in `ChatFrame`.
pub mod chat_frame {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        /// Streamed part (text/tool-call/tool-result/reasoning)
        #[prost(message, tag = "2")]
        Part(super::UiMessagePart),
        #[prost(message, tag = "3")]
        Error(super::StreamError),
        #[prost(message, tag = "4")]
        Heartbeat(super::Heartbeat),
        #[prost(message, tag = "5")]
        Done(super::StreamDone),
        /// Server requests operator approval for a tool call
        #[prost(message, tag = "6")]
        Approval(super::ApprovalRequired),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UiMessagePart {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// "assistant" | "tool" | "system"
    #[prost(string, tag = "2")]
    pub role: ::prost::alloc::string::String,
    /// "text" | "tool-call" | "tool-result" | "reasoning"
    #[prost(string, tag = "3")]
    pub kind: ::prost::alloc::string::String,
    /// JSON bytes matching the AI SDK part shape
    #[prost(bytes = "vec", tag = "4")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApprovalRequired {
    #[prost(string, tag = "1")]
    pub tool_call_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tool_name: ::prost::alloc::string::String,
    /// JSON bytes of the tool call arguments
    #[prost(bytes = "vec", tag = "3")]
    pub tool_input: ::prost::alloc::vec::Vec<u8>,
    /// Human-readable description of what the tool will do
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamError {
    /// Machine-readable error code
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    /// Human-readable error message
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// Whether the client should retry
    #[prost(bool, tag = "3")]
    pub retryable: bool,
    #[prost(uint32, optional, tag = "4")]
    pub retry_after_ms: ::core::option::Option<u32>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Heartbeat {
    #[prost(uint64, tag = "1")]
    pub server_time_ms: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamDone {
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub total_parts: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApproveResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub tool_call_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod chat_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ChatServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ChatServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ChatServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ChatServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ChatServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Stream a chat completion. Returns a stream of ChatFrame events.
        /// The chatbot delegates to agents via forced tool calls; it never executes
        /// backplane operations directly.
        pub async fn send(
            &mut self,
            request: impl tonic::IntoRequest<super::SendRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ChatFrame>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/op_chat.chat.ChatService/Send",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("op_chat.chat.ChatService", "Send"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Approve a tool call that requires operator confirmation.
        /// The chatbot is a delegator — approval gates agent delegation, not direct
        /// execution.
        pub async fn approve(
            &mut self,
            request: impl tonic::IntoRequest<super::ApproveRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ApproveResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/op_chat.chat.ChatService/Approve",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("op_chat.chat.ChatService", "Approve"));
            self.inner.unary(req, path, codec).await
        }
        /// Cancel an in-flight chat stream.
        pub async fn cancel(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelRequest>,
        ) -> std::result::Result<tonic::Response<super::CancelResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/op_chat.chat.ChatService/Cancel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("op_chat.chat.ChatService", "Cancel"));
            self.inner.unary(req, path, codec).await
        }
    }
}
