// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeRequest {
    /// Filter by plugin IDs (empty = all)
    #[prost(string, repeated, tag = "1")]
    pub plugin_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Filter by object paths (glob patterns supported)
    #[prost(string, repeated, tag = "2")]
    pub path_patterns: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Filter by tags
    #[prost(string, repeated, tag = "3")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Include initial state snapshot
    #[prost(bool, tag = "4")]
    pub include_initial_state: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateChange {
    /// Unique change ID
    #[prost(string, tag = "1")]
    pub change_id: ::prost::alloc::string::String,
    /// Event chain event ID
    #[prost(uint64, tag = "2")]
    pub event_id: u64,
    /// Plugin that changed
    #[prost(string, tag = "3")]
    pub plugin_id: ::prost::alloc::string::String,
    /// D-Bus object path
    #[prost(string, tag = "4")]
    pub object_path: ::prost::alloc::string::String,
    /// Change type
    #[prost(enumeration = "ChangeType", tag = "5")]
    pub change_type: i32,
    /// Property/method name (if applicable)
    #[prost(string, tag = "6")]
    pub member_name: ::prost::alloc::string::String,
    /// Previous value (for updates)
    #[prost(message, optional, tag = "7")]
    pub old_value: ::core::option::Option<::prost_types::Value>,
    /// New value
    #[prost(message, optional, tag = "8")]
    pub new_value: ::core::option::Option<::prost_types::Value>,
    /// Tags touched by this change
    #[prost(string, repeated, tag = "9")]
    pub tags_touched: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Event hash for verification
    #[prost(string, tag = "10")]
    pub event_hash: ::prost::alloc::string::String,
    /// Timestamp
    #[prost(message, optional, tag = "11")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Actor who made the change
    #[prost(string, tag = "12")]
    pub actor_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MutateRequest {
    /// Plugin to mutate
    #[prost(string, tag = "1")]
    pub plugin_id: ::prost::alloc::string::String,
    /// D-Bus object path
    #[prost(string, tag = "2")]
    pub object_path: ::prost::alloc::string::String,
    /// Operation type
    #[prost(enumeration = "OperationType", tag = "3")]
    pub operation: i32,
    /// Member (property or method name)
    #[prost(string, tag = "4")]
    pub member_name: ::prost::alloc::string::String,
    /// Arguments/value
    #[prost(message, optional, tag = "5")]
    pub value: ::core::option::Option<::prost_types::Value>,
    /// Actor ID for audit
    #[prost(string, tag = "6")]
    pub actor_id: ::prost::alloc::string::String,
    /// Capability ID for authorization
    #[prost(string, tag = "7")]
    pub capability_id: ::prost::alloc::string::String,
    /// Idempotency key
    #[prost(string, tag = "8")]
    pub idempotency_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MutateResponse {
    /// Whether mutation succeeded
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Event chain event ID
    #[prost(uint64, tag = "2")]
    pub event_id: u64,
    /// Event hash
    #[prost(string, tag = "3")]
    pub event_hash: ::prost::alloc::string::String,
    /// Result value (for method calls)
    #[prost(message, optional, tag = "4")]
    pub result: ::core::option::Option<::prost_types::Value>,
    /// Error details if failed
    #[prost(message, optional, tag = "5")]
    pub error: ::core::option::Option<MutationError>,
    /// Resulting effective state hash
    #[prost(string, tag = "6")]
    pub effective_hash: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MutationError {
    #[prost(enumeration = "ErrorCode", tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// Denial reason from event chain
    #[prost(message, optional, tag = "3")]
    pub deny_reason: ::core::option::Option<DenyReason>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DenyReason {
    #[prost(oneof = "deny_reason::Reason", tags = "1, 2, 3, 4")]
    pub reason: ::core::option::Option<deny_reason::Reason>,
}
/// Nested message and enum types in `DenyReason`.
pub mod deny_reason {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Reason {
        #[prost(message, tag = "1")]
        TagLock(super::TagLock),
        #[prost(message, tag = "2")]
        ConstraintFail(super::ConstraintFail),
        #[prost(message, tag = "3")]
        CapabilityMissing(super::CapabilityMissing),
        #[prost(message, tag = "4")]
        ReadOnlyViolation(super::ReadOnlyViolation),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TagLock {
    #[prost(string, tag = "1")]
    pub tag: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub wrapper_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConstraintFail {
    #[prost(string, tag = "1")]
    pub constraint: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CapabilityMissing {
    #[prost(string, tag = "1")]
    pub capability: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadOnlyViolation {
    #[prost(string, tag = "1")]
    pub field: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStateRequest {
    #[prost(string, tag = "1")]
    pub plugin_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub object_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStateResponse {
    #[prost(message, optional, tag = "1")]
    pub state: ::core::option::Option<::prost_types::Struct>,
    #[prost(string, tag = "2")]
    pub effective_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub at_event_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchMutateRequest {
    #[prost(message, repeated, tag = "1")]
    pub mutations: ::prost::alloc::vec::Vec<MutateRequest>,
    /// All-or-nothing semantics
    #[prost(bool, tag = "2")]
    pub atomic: bool,
    #[prost(string, tag = "3")]
    pub actor_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchMutateResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(message, repeated, tag = "2")]
    pub results: ::prost::alloc::vec::Vec<MutateResponse>,
    /// If atomic and failed, which index failed
    #[prost(int32, tag = "3")]
    pub failed_index: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPluginsResponse {
    #[prost(message, repeated, tag = "1")]
    pub plugins: ::prost::alloc::vec::Vec<PluginInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PluginInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub dbus_path: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "6")]
    pub interfaces: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "7")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSchemaRequest {
    #[prost(string, tag = "1")]
    pub plugin_id: ::prost::alloc::string::String,
    /// Schema format (json-schema-2026, json-schema-draft07, protobuf)
    #[prost(string, tag = "2")]
    pub format: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSchemaResponse {
    #[prost(string, tag = "1")]
    pub schema_json: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dialect: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CallMethodRequest {
    #[prost(string, tag = "1")]
    pub plugin_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub object_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub interface_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub method_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub arguments: ::prost::alloc::vec::Vec<::prost_types::Value>,
    #[prost(string, tag = "6")]
    pub actor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub capability_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CallMethodResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(message, optional, tag = "2")]
    pub result: ::core::option::Option<::prost_types::Value>,
    #[prost(uint64, tag = "3")]
    pub event_id: u64,
    #[prost(string, tag = "4")]
    pub event_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub error: ::core::option::Option<MutationError>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPropertyRequest {
    #[prost(string, tag = "1")]
    pub plugin_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub object_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub interface_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub property_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPropertyResponse {
    #[prost(message, optional, tag = "1")]
    pub value: ::core::option::Option<::prost_types::Value>,
    #[prost(bool, tag = "2")]
    pub read_only: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetPropertyRequest {
    #[prost(string, tag = "1")]
    pub plugin_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub object_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub interface_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub property_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub value: ::core::option::Option<::prost_types::Value>,
    #[prost(string, tag = "6")]
    pub actor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub capability_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetPropertyResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(uint64, tag = "2")]
    pub event_id: u64,
    #[prost(string, tag = "3")]
    pub event_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub error: ::core::option::Option<MutationError>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeSignalsRequest {
    #[prost(string, tag = "1")]
    pub plugin_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub signal_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub object_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Signal {
    #[prost(string, tag = "1")]
    pub plugin_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub object_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub interface_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub signal_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub arguments: ::prost::alloc::vec::Vec<::prost_types::Value>,
    #[prost(message, optional, tag = "6")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEventsRequest {
    #[prost(uint64, tag = "1")]
    pub from_event_id: u64,
    #[prost(uint64, tag = "2")]
    pub to_event_id: u64,
    /// Max events to return
    #[prost(uint32, tag = "3")]
    pub limit: u32,
    /// Filter by plugin
    #[prost(string, tag = "4")]
    pub plugin_id: ::prost::alloc::string::String,
    /// Filter by tags
    #[prost(string, repeated, tag = "5")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Filter by decision
    #[prost(enumeration = "Decision", tag = "6")]
    pub decision_filter: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEventsResponse {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<ChainEvent>,
    #[prost(bool, tag = "2")]
    pub has_more: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChainEvent {
    #[prost(uint64, tag = "1")]
    pub event_id: u64,
    #[prost(string, tag = "2")]
    pub prev_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub event_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "5")]
    pub actor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub capability_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub plugin_id: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub schema_version: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub operation_type: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub target: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "11")]
    pub tags_touched: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration = "Decision", tag = "12")]
    pub decision: i32,
    #[prost(message, optional, tag = "13")]
    pub deny_reason: ::core::option::Option<DenyReason>,
    #[prost(string, tag = "14")]
    pub input_patch_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "15")]
    pub result_effective_hash: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeEventsRequest {
    /// Start from this event ID (0 = latest)
    #[prost(uint64, tag = "1")]
    pub from_event_id: u64,
    /// Filter by plugin
    #[prost(string, tag = "2")]
    pub plugin_id: ::prost::alloc::string::String,
    /// Filter by tags
    #[prost(string, repeated, tag = "3")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct VerifyChainRequest {
    /// Verify from this event
    #[prost(uint64, tag = "1")]
    pub from_event_id: u64,
    /// Verify to this event (0 = latest)
    #[prost(uint64, tag = "2")]
    pub to_event_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyChainResponse {
    #[prost(bool, tag = "1")]
    pub valid: bool,
    #[prost(uint64, tag = "2")]
    pub events_verified: u64,
    #[prost(uint64, tag = "3")]
    pub batches_verified: u64,
    #[prost(string, repeated, tag = "4")]
    pub errors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetProofRequest {
    #[prost(uint64, tag = "1")]
    pub event_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProofResponse {
    #[prost(string, tag = "1")]
    pub event_hash: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub siblings: ::prost::alloc::vec::Vec<MerkleProofSibling>,
    #[prost(string, tag = "3")]
    pub root: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub batch_first_event_id: u64,
    #[prost(uint64, tag = "5")]
    pub batch_last_event_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MerkleProofSibling {
    #[prost(string, tag = "1")]
    pub hash: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_right: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProveTagImmutabilityRequest {
    #[prost(string, tag = "1")]
    pub tag: ::prost::alloc::string::String,
    /// Optional: prove for specific plugin only
    #[prost(string, tag = "2")]
    pub plugin_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProveTagImmutabilityResponse {
    #[prost(string, tag = "1")]
    pub tag: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_immutable: bool,
    #[prost(uint64, repeated, tag = "3")]
    pub violation_event_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, tag = "4")]
    pub total_events_checked: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSnapshotRequest {
    #[prost(string, tag = "1")]
    pub snapshot_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSnapshotResponse {
    #[prost(message, optional, tag = "1")]
    pub snapshot: ::core::option::Option<Snapshot>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSnapshotRequest {
    #[prost(string, tag = "1")]
    pub plugin_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSnapshotResponse {
    #[prost(message, optional, tag = "1")]
    pub snapshot: ::core::option::Option<Snapshot>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Snapshot {
    #[prost(string, tag = "1")]
    pub snapshot_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub at_event_id: u64,
    #[prost(string, tag = "3")]
    pub plugin_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub schema_version: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub stub_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub immutable_wrappers_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub tunable_patch_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub effective_hash: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "9")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "10")]
    pub state: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SearchSemanticTraceRequest {
    /// Max matches to return (0 = server default)
    #[prost(uint32, tag = "1")]
    pub limit: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchSemanticTraceResponse {
    #[prost(string, tag = "1")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub mutation_index: u64,
    #[prost(message, repeated, tag = "3")]
    pub matches: ::prost::alloc::vec::Vec<SemanticTraceMatch>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SemanticTraceMatch {
    #[prost(string, tag = "1")]
    pub point_id: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub score: f32,
    #[prost(message, optional, tag = "3")]
    pub payload: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbListDbsResponse {
    #[prost(string, repeated, tag = "1")]
    pub databases: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbGetSchemaRequest {
    #[prost(string, tag = "1")]
    pub database: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbGetSchemaResponse {
    /// RFC 7047 §3.2 <database-schema> as JSON
    #[prost(string, tag = "1")]
    pub schema_json: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbTransactRequest {
    #[prost(string, tag = "1")]
    pub database: ::prost::alloc::string::String,
    /// RFC 7047 §4.1.3 — array of operations as JSON
    #[prost(string, tag = "2")]
    pub operations_json: ::prost::alloc::string::String,
    /// Actor for event chain audit
    #[prost(string, tag = "3")]
    pub actor_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbTransactResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Array of per-operation results as JSON
    #[prost(string, tag = "2")]
    pub results_json: ::prost::alloc::string::String,
    /// Event chain event ID (if recorded)
    #[prost(uint64, tag = "3")]
    pub event_id: u64,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbMonitorRequest {
    #[prost(string, tag = "1")]
    pub database: ::prost::alloc::string::String,
    /// RFC 7047 §4.1.5 — monitor-requests per table as JSON
    /// e.g. {"Bridge": {}, "Port": {}, "Interface": {}}
    #[prost(string, tag = "2")]
    pub monitor_requests_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbUpdate {
    /// Table name
    #[prost(string, tag = "1")]
    pub table: ::prost::alloc::string::String,
    /// Row UUID
    #[prost(string, tag = "2")]
    pub uuid: ::prost::alloc::string::String,
    /// Old row (null for inserts)
    #[prost(message, optional, tag = "3")]
    pub old_row: ::core::option::Option<::prost_types::Struct>,
    /// New row (null for deletes)
    #[prost(message, optional, tag = "4")]
    pub new_row: ::core::option::Option<::prost_types::Struct>,
    #[prost(message, optional, tag = "5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbEchoRequest {
    #[prost(string, repeated, tag = "1")]
    pub payload: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbEchoResponse {
    #[prost(string, repeated, tag = "1")]
    pub payload: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbDumpDbRequest {
    #[prost(string, tag = "1")]
    pub database: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbDumpDbResponse {
    /// Full database dump as JSON (table → rows)
    #[prost(string, tag = "1")]
    pub dump_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbGetBridgeStateRequest {
    /// Optional: filter by bridge name (empty = all)
    #[prost(string, tag = "1")]
    pub bridge_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbGetBridgeStateResponse {
    #[prost(message, repeated, tag = "1")]
    pub bridges: ::prost::alloc::vec::Vec<OvsdbBridge>,
}
/// RFC 7047 Bridge table — hierarchical view
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbBridge {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub datapath_type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub fail_mode: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub stp_enable: bool,
    #[prost(bool, tag = "5")]
    pub mcast_snooping_enable: bool,
    #[prost(map = "string, string", tag = "6")]
    pub other_config: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, repeated, tag = "7")]
    pub ports: ::prost::alloc::vec::Vec<OvsdbPort>,
}
/// RFC 7047 Port table
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbPort {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// VLAN tag (0 = untagged)
    #[prost(uint32, tag = "2")]
    pub tag: u32,
    #[prost(uint32, repeated, tag = "3")]
    pub trunks: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, tag = "4")]
    pub vlan_mode: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub bond_mode: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub interfaces: ::prost::alloc::vec::Vec<OvsdbInterface>,
}
/// RFC 7047 Interface table
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OvsdbInterface {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// "system" | "internal" | "patch" | "vxlan" | ...
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mac_in_use: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub mac: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub admin_state: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub link_state: ::prost::alloc::string::String,
    /// tunnel options: remote_ip, local_ip, key
    #[prost(map = "string, string", tag = "7")]
    pub options: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuntimeGetSystemInfoResponse {
    #[prost(string, tag = "1")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub kernel_version: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub uptime_seconds: u64,
    #[prost(uint64, tag = "4")]
    pub boot_timestamp: u64,
    #[prost(uint32, tag = "5")]
    pub cpu_count: u32,
    #[prost(uint64, tag = "6")]
    pub memory_total_bytes: u64,
    #[prost(uint64, tag = "7")]
    pub memory_available_bytes: u64,
    #[prost(uint64, tag = "8")]
    pub memory_used_bytes: u64,
    /// "dinit" | "systemd"
    #[prost(string, tag = "9")]
    pub init_system: ::prost::alloc::string::String,
    /// "x86_64" | "aarch64"
    #[prost(string, tag = "10")]
    pub arch: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "11")]
    pub queried_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuntimeListServicesRequest {
    /// Filter by state (empty = all)
    #[prost(string, tag = "1")]
    pub state_filter: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuntimeListServicesResponse {
    #[prost(message, repeated, tag = "1")]
    pub services: ::prost::alloc::vec::Vec<RuntimeServiceInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuntimeGetServiceRequest {
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuntimeServiceInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// "STARTED" | "STOPPED" | "STARTING" | "STOPPING"
    #[prost(string, tag = "2")]
    pub state: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub pid: u32,
    #[prost(bool, tag = "4")]
    pub enabled: bool,
    #[prost(string, tag = "5")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "6")]
    pub dependencies: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "7")]
    pub started_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuntimeStreamMetricsRequest {
    /// Interval in seconds between updates (default: 5)
    #[prost(uint32, tag = "1")]
    pub interval_seconds: u32,
    /// Which metric categories to include (empty = all)
    ///
    /// "cpu" | "memory" | "network" | "disk"
    #[prost(string, repeated, tag = "2")]
    pub categories: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuntimeMetricUpdate {
    #[prost(string, tag = "1")]
    pub category: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub value: f64,
    #[prost(string, tag = "4")]
    pub unit: ::prost::alloc::string::String,
    /// e.g. {"interface": "ens3", "direction": "rx"}
    #[prost(map = "string, string", tag = "5")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "6")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuntimeListInterfacesResponse {
    #[prost(message, repeated, tag = "1")]
    pub interfaces: ::prost::alloc::vec::Vec<RuntimeNetworkInterface>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuntimeNetworkInterface {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub index: u32,
    #[prost(string, tag = "3")]
    pub mac_address: ::prost::alloc::string::String,
    /// "UP" | "DOWN" | "UNKNOWN"
    #[prost(string, tag = "4")]
    pub state: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub mtu: u32,
    #[prost(string, repeated, tag = "6")]
    pub ipv4_addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "7")]
    pub ipv6_addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, tag = "8")]
    pub rx_bytes: u64,
    #[prost(uint64, tag = "9")]
    pub tx_bytes: u64,
    #[prost(uint64, tag = "10")]
    pub rx_packets: u64,
    #[prost(uint64, tag = "11")]
    pub tx_packets: u64,
    #[prost(string, tag = "12")]
    pub driver: ::prost::alloc::string::String,
    #[prost(uint32, tag = "13")]
    pub speed_mbps: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuntimeGetNumaTopologyResponse {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<NumaNode>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumaNode {
    #[prost(uint32, tag = "1")]
    pub node_id: u32,
    #[prost(uint32, repeated, tag = "2")]
    pub cpus: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint64, tag = "3")]
    pub memory_total_bytes: u64,
    #[prost(uint64, tag = "4")]
    pub memory_free_bytes: u64,
    #[prost(uint64, tag = "5")]
    pub memory_used_bytes: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbusCallRequest {
    /// "session" | "system"
    #[prost(string, tag = "1")]
    pub bus: ::prost::alloc::string::String,
    /// e.g. "ai.assistant.v1"
    #[prost(string, tag = "2")]
    pub destination: ::prost::alloc::string::String,
    /// e.g. "/ai/assistant"
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    /// e.g. "ai.assistant.v1"
    #[prost(string, tag = "4")]
    pub interface: ::prost::alloc::string::String,
    /// e.g. "GetSoulMemory"
    #[prost(string, tag = "5")]
    pub method: ::prost::alloc::string::String,
    /// JSON-encoded argument(s)
    #[prost(string, tag = "6")]
    pub json_body: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbusCallResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// JSON-encoded return value
    #[prost(string, tag = "2")]
    pub json_result: ::prost::alloc::string::String,
    /// error message if failed
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbusGetPropertyRequest {
    #[prost(string, tag = "1")]
    pub bus: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub destination: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub interface: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub property: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbusGetPropertyResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub json_value: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbusSetPropertyRequest {
    #[prost(string, tag = "1")]
    pub bus: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub destination: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub interface: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub property: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub json_value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbusSetPropertyResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbusWatchRequest {
    #[prost(string, tag = "1")]
    pub bus: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub destination: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub interface: ::prost::alloc::string::String,
    /// empty = all signals
    #[prost(string, repeated, tag = "5")]
    pub signal_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbusSignalEvent {
    #[prost(string, tag = "1")]
    pub signal_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub interface: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub json_body: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelRouteProto {
    #[prost(string, tag = "1")]
    pub hint: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub provider: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub available: bool,
    #[prost(string, tag = "5")]
    pub effort_level: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub privacy_tier: ::prost::alloc::string::String,
    #[prost(uint32, tag = "7")]
    pub context_window: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProviderProto {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub route: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub kind: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZeroclawProjection {
    #[prost(string, tag = "1")]
    pub schema_json: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub model_routes: ::prost::alloc::vec::Vec<ModelRouteProto>,
    #[prost(message, repeated, tag = "3")]
    pub providers: ::prost::alloc::vec::Vec<ProviderProto>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ChangeType {
    Unspecified = 0,
    PropertySet = 1,
    PropertyDelete = 2,
    MethodCall = 3,
    Signal = 4,
    ObjectAdded = 5,
    ObjectRemoved = 6,
    SchemaMigration = 7,
}
impl ChangeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CHANGE_TYPE_UNSPECIFIED",
            Self::PropertySet => "CHANGE_TYPE_PROPERTY_SET",
            Self::PropertyDelete => "CHANGE_TYPE_PROPERTY_DELETE",
            Self::MethodCall => "CHANGE_TYPE_METHOD_CALL",
            Self::Signal => "CHANGE_TYPE_SIGNAL",
            Self::ObjectAdded => "CHANGE_TYPE_OBJECT_ADDED",
            Self::ObjectRemoved => "CHANGE_TYPE_OBJECT_REMOVED",
            Self::SchemaMigration => "CHANGE_TYPE_SCHEMA_MIGRATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHANGE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CHANGE_TYPE_PROPERTY_SET" => Some(Self::PropertySet),
            "CHANGE_TYPE_PROPERTY_DELETE" => Some(Self::PropertyDelete),
            "CHANGE_TYPE_METHOD_CALL" => Some(Self::MethodCall),
            "CHANGE_TYPE_SIGNAL" => Some(Self::Signal),
            "CHANGE_TYPE_OBJECT_ADDED" => Some(Self::ObjectAdded),
            "CHANGE_TYPE_OBJECT_REMOVED" => Some(Self::ObjectRemoved),
            "CHANGE_TYPE_SCHEMA_MIGRATION" => Some(Self::SchemaMigration),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OperationType {
    Unspecified = 0,
    SetProperty = 1,
    CallMethod = 2,
    ApplyPatch = 3,
}
impl OperationType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPERATION_TYPE_UNSPECIFIED",
            Self::SetProperty => "OPERATION_TYPE_SET_PROPERTY",
            Self::CallMethod => "OPERATION_TYPE_CALL_METHOD",
            Self::ApplyPatch => "OPERATION_TYPE_APPLY_PATCH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPERATION_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "OPERATION_TYPE_SET_PROPERTY" => Some(Self::SetProperty),
            "OPERATION_TYPE_CALL_METHOD" => Some(Self::CallMethod),
            "OPERATION_TYPE_APPLY_PATCH" => Some(Self::ApplyPatch),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    Unspecified = 0,
    NotFound = 1,
    PermissionDenied = 2,
    ValidationFailed = 3,
    ReadOnly = 4,
    TagLocked = 5,
    Internal = 6,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ERROR_CODE_UNSPECIFIED",
            Self::NotFound => "ERROR_CODE_NOT_FOUND",
            Self::PermissionDenied => "ERROR_CODE_PERMISSION_DENIED",
            Self::ValidationFailed => "ERROR_CODE_VALIDATION_FAILED",
            Self::ReadOnly => "ERROR_CODE_READ_ONLY",
            Self::TagLocked => "ERROR_CODE_TAG_LOCKED",
            Self::Internal => "ERROR_CODE_INTERNAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ERROR_CODE_UNSPECIFIED" => Some(Self::Unspecified),
            "ERROR_CODE_NOT_FOUND" => Some(Self::NotFound),
            "ERROR_CODE_PERMISSION_DENIED" => Some(Self::PermissionDenied),
            "ERROR_CODE_VALIDATION_FAILED" => Some(Self::ValidationFailed),
            "ERROR_CODE_READ_ONLY" => Some(Self::ReadOnly),
            "ERROR_CODE_TAG_LOCKED" => Some(Self::TagLocked),
            "ERROR_CODE_INTERNAL" => Some(Self::Internal),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Decision {
    Unspecified = 0,
    Allow = 1,
    Deny = 2,
}
impl Decision {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DECISION_UNSPECIFIED",
            Self::Allow => "DECISION_ALLOW",
            Self::Deny => "DECISION_DENY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DECISION_UNSPECIFIED" => Some(Self::Unspecified),
            "DECISION_ALLOW" => Some(Self::Allow),
            "DECISION_DENY" => Some(Self::Deny),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod state_sync_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Bidirectional state sync between D-Bus and gRPC clients
    #[derive(Debug, Clone)]
    pub struct StateSyncClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl StateSyncClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> StateSyncClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> StateSyncClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            StateSyncClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Subscribe to all state changes (D-Bus -> gRPC streaming)
        pub async fn subscribe(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscribeRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::StateChange>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.StateSync/Subscribe",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.StateSync", "Subscribe"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Apply a mutation (gRPC -> D-Bus -> Event Chain)
        pub async fn mutate(
            &mut self,
            request: impl tonic::IntoRequest<super::MutateRequest>,
        ) -> std::result::Result<tonic::Response<super::MutateResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.StateSync/Mutate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.StateSync", "Mutate"));
            self.inner.unary(req, path, codec).await
        }
        /// Get current state snapshot
        pub async fn get_state(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.StateSync/GetState",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.StateSync", "GetState"));
            self.inner.unary(req, path, codec).await
        }
        /// Batch mutations (transactional)
        pub async fn batch_mutate(
            &mut self,
            request: impl tonic::IntoRequest<super::BatchMutateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BatchMutateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.StateSync/BatchMutate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.StateSync", "BatchMutate"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod plugin_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct PluginServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PluginServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PluginServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PluginServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PluginServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// List all registered plugins
        pub async fn list_plugins(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<
            tonic::Response<super::ListPluginsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.PluginService/ListPlugins",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.PluginService", "ListPlugins"));
            self.inner.unary(req, path, codec).await
        }
        /// Get plugin schema (JSON Schema 2026)
        pub async fn get_schema(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSchemaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.PluginService/GetSchema",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.PluginService", "GetSchema"));
            self.inner.unary(req, path, codec).await
        }
        /// Call a plugin method
        pub async fn call_method(
            &mut self,
            request: impl tonic::IntoRequest<super::CallMethodRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CallMethodResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.PluginService/CallMethod",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.PluginService", "CallMethod"));
            self.inner.unary(req, path, codec).await
        }
        /// Get/Set property
        pub async fn get_property(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPropertyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPropertyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.PluginService/GetProperty",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.PluginService", "GetProperty"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn set_property(
            &mut self,
            request: impl tonic::IntoRequest<super::SetPropertyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetPropertyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.PluginService/SetProperty",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.PluginService", "SetProperty"));
            self.inner.unary(req, path, codec).await
        }
        /// Subscribe to plugin signals
        pub async fn subscribe_signals(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscribeSignalsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Signal>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.PluginService/SubscribeSignals",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("operation.v1.PluginService", "SubscribeSignals"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod event_chain_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct EventChainServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl EventChainServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> EventChainServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> EventChainServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            EventChainServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Get events in range
        pub async fn get_events(
            &mut self,
            request: impl tonic::IntoRequest<super::GetEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetEventsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.EventChainService/GetEvents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.EventChainService", "GetEvents"));
            self.inner.unary(req, path, codec).await
        }
        /// Subscribe to new events as they occur
        pub async fn subscribe_events(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscribeEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ChainEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.EventChainService/SubscribeEvents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("operation.v1.EventChainService", "SubscribeEvents"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Verify chain integrity
        pub async fn verify_chain(
            &mut self,
            request: impl tonic::IntoRequest<super::VerifyChainRequest>,
        ) -> std::result::Result<
            tonic::Response<super::VerifyChainResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.EventChainService/VerifyChain",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("operation.v1.EventChainService", "VerifyChain"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get Merkle proof for an event
        pub async fn get_proof(
            &mut self,
            request: impl tonic::IntoRequest<super::GetProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetProofResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.EventChainService/GetProof",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.EventChainService", "GetProof"));
            self.inner.unary(req, path, codec).await
        }
        /// Prove tag immutability
        pub async fn prove_tag_immutability(
            &mut self,
            request: impl tonic::IntoRequest<super::ProveTagImmutabilityRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ProveTagImmutabilityResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.EventChainService/ProveTagImmutability",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "operation.v1.EventChainService",
                        "ProveTagImmutability",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get/Create snapshot
        pub async fn get_snapshot(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSnapshotRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSnapshotResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.EventChainService/GetSnapshot",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("operation.v1.EventChainService", "GetSnapshot"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn create_snapshot(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateSnapshotRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateSnapshotResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.EventChainService/CreateSnapshot",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("operation.v1.EventChainService", "CreateSnapshot"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Trace-scoped semantic lookup for the Accountability pane
        pub async fn search_semantic_trace(
            &mut self,
            request: impl tonic::IntoRequest<super::SearchSemanticTraceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SearchSemanticTraceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.EventChainService/SearchSemanticTrace",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "operation.v1.EventChainService",
                        "SearchSemanticTrace",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod ovsdb_mirror_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// 1:1 gRPC projection of the OVSDB management protocol (RFC 7047).
    /// All operations pass through to ovsdb-server via the D-Bus mirror.
    #[derive(Debug, Clone)]
    pub struct OvsdbMirrorClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl OvsdbMirrorClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> OvsdbMirrorClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> OvsdbMirrorClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            OvsdbMirrorClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// RFC 7047 §4.1.1 — List available databases
        pub async fn list_dbs(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<
            tonic::Response<super::OvsdbListDbsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.OvsdbMirror/ListDbs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.OvsdbMirror", "ListDbs"));
            self.inner.unary(req, path, codec).await
        }
        /// RFC 7047 §4.1.2 — Get database schema (<database-schema>)
        pub async fn get_schema(
            &mut self,
            request: impl tonic::IntoRequest<super::OvsdbGetSchemaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OvsdbGetSchemaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.OvsdbMirror/GetSchema",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.OvsdbMirror", "GetSchema"));
            self.inner.unary(req, path, codec).await
        }
        /// RFC 7047 §4.1.3 — Execute a transaction (insert/select/update/mutate/delete/wait)
        pub async fn transact(
            &mut self,
            request: impl tonic::IntoRequest<super::OvsdbTransactRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OvsdbTransactResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.OvsdbMirror/Transact",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.OvsdbMirror", "Transact"));
            self.inner.unary(req, path, codec).await
        }
        /// RFC 7047 §4.1.5 — Monitor database changes (streaming)
        pub async fn monitor(
            &mut self,
            request: impl tonic::IntoRequest<super::OvsdbMonitorRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::OvsdbUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.OvsdbMirror/Monitor",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.OvsdbMirror", "Monitor"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// RFC 7047 §4.1.11 — Echo for liveness
        pub async fn echo(
            &mut self,
            request: impl tonic::IntoRequest<super::OvsdbEchoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OvsdbEchoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.OvsdbMirror/Echo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.OvsdbMirror", "Echo"));
            self.inner.unary(req, path, codec).await
        }
        /// Dump full database state (convenience, not in RFC)
        pub async fn dump_db(
            &mut self,
            request: impl tonic::IntoRequest<super::OvsdbDumpDbRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OvsdbDumpDbResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.OvsdbMirror/DumpDb",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.OvsdbMirror", "DumpDb"));
            self.inner.unary(req, path, codec).await
        }
        /// Get the full Bridge→Port→Interface hierarchy (reconciled mirror view)
        pub async fn get_bridge_state(
            &mut self,
            request: impl tonic::IntoRequest<super::OvsdbGetBridgeStateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OvsdbGetBridgeStateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.OvsdbMirror/GetBridgeState",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.OvsdbMirror", "GetBridgeState"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod runtime_mirror_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Live runtime state: process info, services, system metrics.
    /// Not stored in any database — queried directly from the running system.
    #[derive(Debug, Clone)]
    pub struct RuntimeMirrorClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RuntimeMirrorClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RuntimeMirrorClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RuntimeMirrorClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RuntimeMirrorClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Get overall system runtime info
        pub async fn get_system_info(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<
            tonic::Response<super::RuntimeGetSystemInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.RuntimeMirror/GetSystemInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.RuntimeMirror", "GetSystemInfo"));
            self.inner.unary(req, path, codec).await
        }
        /// List dinit services and their states
        pub async fn list_services(
            &mut self,
            request: impl tonic::IntoRequest<super::RuntimeListServicesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RuntimeListServicesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.RuntimeMirror/ListServices",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.RuntimeMirror", "ListServices"));
            self.inner.unary(req, path, codec).await
        }
        /// Get a specific service's state
        pub async fn get_service(
            &mut self,
            request: impl tonic::IntoRequest<super::RuntimeGetServiceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RuntimeServiceInfo>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.RuntimeMirror/GetService",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.RuntimeMirror", "GetService"));
            self.inner.unary(req, path, codec).await
        }
        /// Stream live metric updates (CPU, memory, network counters)
        pub async fn stream_metrics(
            &mut self,
            request: impl tonic::IntoRequest<super::RuntimeStreamMetricsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::RuntimeMetricUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.RuntimeMirror/StreamMetrics",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.RuntimeMirror", "StreamMetrics"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Get network interface states (from rtnetlink)
        pub async fn list_interfaces(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<
            tonic::Response<super::RuntimeListInterfacesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.RuntimeMirror/ListInterfaces",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.RuntimeMirror", "ListInterfaces"));
            self.inner.unary(req, path, codec).await
        }
        /// Get NUMA topology
        pub async fn get_numa_topology(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<
            tonic::Response<super::RuntimeGetNumaTopologyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.RuntimeMirror/GetNumaTopology",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("operation.v1.RuntimeMirror", "GetNumaTopology"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated client implementations.
pub mod dbus_passthrough_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Generic D-Bus method call passthrough. Allows gRPC-Web clients (browser UI)
    /// to invoke any method on any D-Bus interface reachable from the session or
    /// system bus. This is the extension point for services that register on the
    /// bus (e.g. ai.assistant.v1) without needing dedicated gRPC proto definitions.
    #[derive(Debug, Clone)]
    pub struct DbusPassthroughClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl DbusPassthroughClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> DbusPassthroughClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> DbusPassthroughClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            DbusPassthroughClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Call a D-Bus method and return the JSON result.
        pub async fn call(
            &mut self,
            request: impl tonic::IntoRequest<super::DbusCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DbusCallResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.DbusPassthrough/Call",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.DbusPassthrough", "Call"));
            self.inner.unary(req, path, codec).await
        }
        /// Get a D-Bus property value as JSON.
        pub async fn get(
            &mut self,
            request: impl tonic::IntoRequest<super::DbusGetPropertyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DbusGetPropertyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.DbusPassthrough/Get",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.DbusPassthrough", "Get"));
            self.inner.unary(req, path, codec).await
        }
        /// Set a D-Bus property value from JSON.
        pub async fn set(
            &mut self,
            request: impl tonic::IntoRequest<super::DbusSetPropertyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DbusSetPropertyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.DbusPassthrough/Set",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.DbusPassthrough", "Set"));
            self.inner.unary(req, path, codec).await
        }
        /// Subscribe to a D-Bus signal, streaming events as JSON.
        pub async fn watch(
            &mut self,
            request: impl tonic::IntoRequest<super::DbusWatchRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::DbusSignalEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/operation.v1.DbusPassthrough/Watch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("operation.v1.DbusPassthrough", "Watch"));
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
