//! identity_sled — the container IS the sled IS the identity.
//!
//! Each record is one provisioned container's identity, seeded by its sealed
//! blob: `session_id` (= the container name, derived from the WireGuard
//! pubkey) keys the record; the host itself is "container zero" — the same
//! kind of object, not a special case. This replaces the bespoke pre-schema
//! `#[repr(C)]` sled at `/dev/shm/plugin_schema.dat` as the schema'd,
//! reflectable identity surface; that global last-write-wins file is retired
//! and no longer written or read by any identity path.
//!
//! The session event ledger ("snowball") methods replace the flat
//! `/dev/shm/snowball_session.log`; every call is already notarized in the
//! immutable event chain by MutationEngine, and rows persist to the Cozo
//! `sessions` / `session_memories` relations via the cognitive-mcp store.

use anyhow::Result;
use async_trait::async_trait;
use op_state::{ApplyResult, Checkpoint, DiffMetadata, PluginCapabilities, StateDiff, StatePlugin};
use op_state_store::PluginSchema;
use serde::{Deserialize, Serialize};
use simd_json::prelude::*;
use simd_json::OwnedValue as Value;

/// Record format discriminator for `ContainerIdentitySled`.
///
/// Version ≤ 2: legacy records carrying `hashed_footprint` (the old
/// etch_footprint-derived value). Version 3: genesis-based records.
/// Human-set; changes only on a deliberate format generation.
pub const RECORD_FORMAT: u32 = 3;

/// Content hash of the `ContainerIdentitySled` record shape. Generated by
/// `build.rs` from the canonical struct definition. Changes automatically
/// when any field is added, removed, reordered, or retyped. Consumers compare
/// at load time for drift detection.
pub const SCHEMA_CONTENT_HASH: &str =
    include_str!(concat!(env!("OUT_DIR"), "/identity_sled_schema_hash.txt"));

/// One container's identity sled. The container is the sled is the identity:
/// `session_id` == container name == derived session identity.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "sch.service.identity-sled.record.schema@v1"))]
pub struct ContainerIdentitySled {
    /// Container identity: session_id = container name, derived from the
    /// WireGuard pubkey. The host is "container zero" under its own id.
    #[schemars(extend("x-oscal-subid" = "src.service.identity-sled.session-id@v1"))]
    pub session_id: String,
    /// WireGuard public key (base64) — the cryptographic root of identity.
    #[schemars(extend("x-oscal-subid" = "src.network.identity-sled.wireguard-pubkey@v1"))]
    pub wireguard_pubkey: String,
    /// WireGuard interface the identity is anchored to.
    #[serde(default)]
    pub interface: String,
    /// Peer IP on the WG mesh, when known (identity anchor for sub-HTTP protocols).
    #[serde(default)]
    pub peer_ip: Option<String>,
    /// Monotonic mutation index (accountability loop position).
    #[serde(default)]
    pub mutation_index: u64,
    /// Hex blake3 session genesis — the immutable identity anchor, minted once
    /// at arrival (first authenticated mutation) and never recomputed.
    /// Replaces the v2 `hashed_footprint` field; the serde alias lets old v2
    /// records deserialize into this field during migration.
    #[serde(default, alias = "hashed_footprint")]
    pub genesis: Option<String>,
    /// Hex trace id propagated across the session.
    #[serde(default)]
    pub trace_id: String,
    /// Published schema catalog version the footprint was etched against.
    #[serde(default)]
    pub schema_version: u32,
    /// Semantic vector id for the session, when embedded.
    #[serde(default)]
    pub vector_id: String,
    /// Sealed identity blob backing this sled in the SHM catalog
    /// (`<plugin_id>.<schema_hash16>.blob`). The blob seeds the container.
    #[serde(default)]
    #[schemars(extend("x-oscal-subid" = "src.service.identity-sled.blob-ref@v1"))]
    pub blob_ref: Option<String>,
    /// The sled's persistence: an immutable sealed btrfs image, registered as
    /// a first-class btrfs device record in Cozo and attached via
    /// `btrfs device add` — no overlay layers, no subvolumes.
    #[serde(default)]
    #[schemars(extend("x-oscal-subid" = "src.service.identity-sled.btrfs-device@v1"))]
    pub btrfs_device: Option<SledBtrfsDevice>,
    /// The container's full Incus definition (official `shared/api` shape) —
    /// the sled inherits the Incus schema; provisioning the container IS
    /// writing this sled. The instance `name` is always the session_id.
    #[serde(default)]
    #[schemars(extend("x-oscal-subid" = "src.service.identity-sled.instance@v1"))]
    pub instance: Option<super::incus::IncusInstance>,
    /// Unix seconds when the session began.
    #[serde(default)]
    pub session_started_at: i64,
    /// Unix seconds of the last heartbeat / arrival.
    #[serde(default)]
    pub last_seen_at: i64,
    /// Whether the identity is currently live (container running / host up).
    #[serde(default)]
    pub active: bool,
    /// Unix seconds the *current visit/term* stops being valid. The account
    /// (session_id) can be lifelong (host/user/chatbot) while still having a
    /// bounded term — lifelong accounts get this renewed on every touch
    /// (`touch_identity_sled`); temporary consumer identities (e.g. external
    /// frontends like Lovable) don't, so their term actually lapses.
    /// `None` before a term has ever been issued.
    #[serde(default)]
    #[schemars(extend("x-oscal-subid" = "src.service.identity-sled.expires-at@v1"))]
    pub expires_at: Option<i64>,
    /// Unix seconds of the arrival event (first authenticated mutation).
    /// Stored immutably for offline re-verification.
    #[serde(default)]
    pub arrival_timestamp: i64,
    /// Hex hash of the chain head at genesis mint time.
    #[serde(default)]
    pub chain_head_at_arrival: String,
    /// Hex hash of the schema catalog at genesis mint time.
    #[serde(default)]
    pub catalog_hash_at_arrival: String,
    /// Timestamp of the chain head event at genesis mint time.
    #[serde(default)]
    pub head_timestamp_at_arrival: i64,
}

impl ContainerIdentitySled {
    /// Whether this account's arrival has been anchored by `mint_genesis`.
    ///
    /// A non-empty `genesis` is not sufficient on its own. A version-2 record's
    /// `hashed_footprint` lands in `genesis` through the serde alias above, so
    /// it *looks* anchored while carrying a value that was never minted and has
    /// no inputs behind it — nothing could re-derive or re-verify it. An anchor
    /// counts only when the inputs it was minted from came with it.
    ///
    /// This is the one definition of "anchored". The accept path uses it to
    /// decide whether to mint, and the write path uses it to decide whether a
    /// record may be overwritten; if they disagreed, a v2 record would be
    /// rejected forever by one and refused a mint by the other.
    pub fn is_anchored(&self) -> bool {
        self.genesis.as_deref().is_some_and(|g| !g.is_empty())
            && self.arrival_timestamp != 0
            && !self.chain_head_at_arrival.is_empty()
    }
}

/// The btrfs device that IS the sled's persistence. The record of truth lives
/// in Cozo (the device registry); the physical attach is `btrfs device add`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "sch.service.identity-sled.btrfs-device.schema@v1"))]
pub struct SledBtrfsDevice {
    /// Path of the sealed image / block device (e.g. loop-backed image file).
    pub device_path: String,
    /// Mounted btrfs filesystem the device is added TO (`btrfs device add
    /// <device_path> <mount_point>`).
    #[serde(default)]
    pub mount_point: String,
    /// btrfs filesystem UUID of the sealed image.
    #[serde(default)]
    pub btrfs_uuid: String,
    /// Cozo row id of the device record (the registry of truth).
    #[serde(default)]
    pub cozo_id: String,
    /// Whether the device is currently attached (`btrfs device add` done).
    #[serde(default)]
    pub attached: bool,
}

/// One entry in a session's append-only "snowball" ledger.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "sch.service.identity-sled.session-event.schema@v1"))]
pub struct SessionEvent {
    /// Session the event belongs to.
    pub session_id: String,
    /// Monotonic sequence within the session.
    pub seq: u64,
    /// Event kind (e.g. "arrival", "mutation", "handshake").
    pub kind: String,
    /// OSCAL subid of the acting surface, when applicable.
    #[serde(default)]
    pub subid: String,
    /// JSON payload of the event.
    #[serde(default)]
    pub content: String,
    /// Unix seconds the event was recorded.
    pub created_at: i64,
}

/// Runtime state: every container identity sled, host ("container zero") included.
#[derive(Debug, Clone, Serialize, Deserialize, Default, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "sch.service.plugin.identity-sled.schema@v1"))]
#[schemars(extend("x-oscal-category" = "service"))]
pub struct IdentitySledState {
    /// All known container identity sleds, keyed by `session_id`, sorted.
    #[schemars(extend("x-oscal-subid" = "obs.service.identity-sled.sleds@v1"))]
    pub sleds: Vec<ContainerIdentitySled>,
}

pub struct IdentitySledPlugin;

impl IdentitySledPlugin {
    pub fn new() -> Self {
        Self
    }

    /// This plugin's present state, read from its own sealed blob in the SHM
    /// catalog (the blob IS the plugin).
    fn read_state() -> IdentitySledState {
        let Some(schema) = op_blob::catalog::read_plugin_schema_shm("identity_sled") else {
            return IdentitySledState::default();
        };
        let Some(state) = schema.example else {
            return IdentitySledState::default();
        };
        simd_json::serde::from_owned_value::<IdentitySledState>(state).unwrap_or_default()
    }
}

impl Default for IdentitySledPlugin {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl StatePlugin for IdentitySledPlugin {
    fn name(&self) -> &str {
        "identity_sled"
    }

    fn version(&self) -> &str {
        "1.0.0"
    }

    fn schema(&self) -> Option<PluginSchema> {
        let mut schema = super::plugin_scaffold_helpers::identity_sled_plugin_schema();
        super::common::oscal::ensure_category_metadata_fields(&mut schema);
        Some(schema)
    }

    async fn calculate_diff(&self, _current: &Value, _desired: &Value) -> Result<StateDiff> {
        Ok(StateDiff {
            plugin: self.name().to_string(),
            actions: vec![],
            metadata: DiffMetadata {
                timestamp: chrono::Utc::now().timestamp(),
                current_hash: "schema".to_string(),
                desired_hash: "schema".to_string(),
            },
        })
    }

    async fn apply_state(&self, _diff: &StateDiff) -> Result<ApplyResult> {
        // Mutations go through the identity_sled dispatcher (MutationEngine);
        // reconciliation has nothing to converge here.
        Ok(ApplyResult {
            success: true,
            changes_applied: vec![],
            errors: vec![],
            checkpoint: None,
        })
    }

    async fn verify_state(&self, _desired: &Value) -> Result<bool> {
        Ok(true)
    }

    async fn create_checkpoint(&self) -> Result<Checkpoint> {
        Ok(Checkpoint {
            id: uuid::Uuid::new_v4().to_string(),
            plugin: self.name().to_string(),
            timestamp: chrono::Utc::now().timestamp(),
            state_snapshot: simd_json::serde::to_owned_value(Self::read_state())?,
            backend_checkpoint: None,
        })
    }

    async fn rollback(&self, _checkpoint: &Checkpoint) -> Result<()> {
        Ok(())
    }

    fn capabilities(&self) -> PluginCapabilities {
        PluginCapabilities {
            supports_rollback: false,
            supports_checkpoints: true,
            supports_verification: true,
            atomic_operations: false,
        }
    }
}

/// Canonical `identity_sled` schema derived from [`IdentitySledState`] via
/// schemars, plus the callable method surface.
pub(crate) fn identity_sled_schema() -> PluginSchema {
    let root = serde_json::to_value(schemars::schema_for!(IdentitySledState))
        .expect("schemars schema serializes to JSON");
    let mut schema = super::schemars_adapter::plugin_schema_from_json(
        "identity_sled",
        "1.0.0",
        "Container identity sleds: the container is the sled is the identity; host is container zero; each record is seeded by its sealed blob",
        &root,
    );

    // Typed method inputs / outputs.
    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct GetIdentityInput {
        /// Session (container) id to read; empty = the host ("container zero").
        #[serde(default)]
        pub session_id: String,
    }
    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct GetIdentityOutput {
        pub identity: ContainerIdentitySled,
    }
    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct WriteIdentityInput {
        /// WireGuard public key (base64). session_id is DERIVED from this —
        /// never supplied — so an identity cannot be written under a foreign id.
        pub wireguard_pubkey: String,
        #[serde(default)]
        pub interface: String,
        #[serde(default)]
        pub peer_ip: Option<String>,
        /// Sealed identity blob reference seeding this container.
        #[serde(default)]
        pub blob_ref: Option<String>,
        /// btrfs device (Cozo-registered, `btrfs device add`-attached) that is
        /// this sled's persistence.
        #[serde(default)]
        pub btrfs_device: Option<SledBtrfsDevice>,
    }
    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct ProvisionContainerInput {
        /// WireGuard public key (base64). session_id — and therefore the
        /// container name — is DERIVED from this, never supplied.
        pub wireguard_pubkey: String,
        /// Provision-time PSK (base64); when present the session_id derivation
        /// is Argon2(PSK, salt=pubkey).
        #[serde(default)]
        pub psk: Option<String>,
        /// Sealed identity blob reference seeding this container.
        #[serde(default)]
        pub blob_ref: Option<String>,
        /// btrfs persistence device to register for this sled.
        #[serde(default)]
        pub btrfs_device: Option<SledBtrfsDevice>,
        /// Incus instance definition overrides (image, profiles, config,
        /// devices…). `name` is ignored and forced to the derived session_id;
        /// `nic`-type devices are rejected (containers get no NIC or IP).
        #[serde(default)]
        pub instance: Option<super::incus::IncusInstance>,
    }
    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct AttachBtrfsDeviceInput {
        pub session_id: String,
    }
    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct TouchSessionInput {
        pub session_id: String,
    }
    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct RecordSessionEventInput {
        pub session_id: String,
        /// Event kind (e.g. "arrival", "mutation", "handshake").
        pub kind: String,
        #[serde(default)]
        pub subid: String,
        /// JSON payload of the event.
        #[serde(default)]
        pub content: String,
    }
    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct GetSessionHistoryInput {
        pub session_id: String,
        /// Maximum entries to return, newest first (0 = all).
        #[serde(default)]
        pub limit: u32,
    }
    #[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
    pub struct GetSessionHistoryOutput {
        pub events: Vec<SessionEvent>,
    }

    use super::plugin_scaffold_helpers::method_decl_from_schemars_with_output;
    use super::plugin_scaffold_helpers::AckOutput;
    use op_state_store::SideEffect;

    schema.methods.insert(
        "get_identity".to_string(),
        method_decl_from_schemars_with_output::<GetIdentityInput, GetIdentityOutput>(
            "get_identity",
            SideEffect::Read,
            true,
            "identity_sled.read",
            "obs.service.identity-sled.identity.get@v1",
        ),
    );
    schema.methods.insert(
        "write_identity".to_string(),
        method_decl_from_schemars_with_output::<WriteIdentityInput, GetIdentityOutput>(
            "write_identity",
            SideEffect::Mutation,
            true,
            "identity_sled.write",
            "mut.service.identity-sled.identity.write@v1",
        ),
    );
    schema.methods.insert(
        "provision_container".to_string(),
        method_decl_from_schemars_with_output::<ProvisionContainerInput, GetIdentityOutput>(
            "provision_container",
            SideEffect::Mutation,
            false,
            "identity_sled.write",
            "mut.service.identity-sled.container.provision@v1",
        ),
    );
    schema.methods.insert(
        "attach_btrfs_device".to_string(),
        method_decl_from_schemars_with_output::<AttachBtrfsDeviceInput, GetIdentityOutput>(
            "attach_btrfs_device",
            SideEffect::Mutation,
            false,
            "identity_sled.write",
            "mut.service.identity-sled.btrfs-device.attach@v1",
        ),
    );
    schema.methods.insert(
        "touch_session".to_string(),
        method_decl_from_schemars_with_output::<TouchSessionInput, AckOutput>(
            "touch_session",
            SideEffect::Mutation,
            true,
            "identity_sled.write",
            "mut.service.identity-sled.session.touch@v1",
        ),
    );
    schema.methods.insert(
        "record_session_event".to_string(),
        method_decl_from_schemars_with_output::<RecordSessionEventInput, AckOutput>(
            "record_session_event",
            SideEffect::Mutation,
            false,
            "identity_sled.write",
            "mut.service.identity-sled.session.event.record@v1",
        ),
    );
    schema.methods.insert(
        "get_session_history".to_string(),
        method_decl_from_schemars_with_output::<GetSessionHistoryInput, GetSessionHistoryOutput>(
            "get_session_history",
            SideEffect::Read,
            true,
            "identity_sled.read",
            "obs.service.identity-sled.session.history.get@v1",
        ),
    );

    schema.capabilities.insert(
        "identity_sled.read".to_string(),
        op_state_store::CapabilityDecl {
            id: "identity_sled.read".to_string(),
            description: "Grants: get_identity, get_session_history.".to_string(),
        },
    );
    schema.capabilities.insert(
        "identity_sled.write".to_string(),
        op_state_store::CapabilityDecl {
            id: "identity_sled.write".to_string(),
            description: "Grants: write_identity, provision_container, attach_btrfs_device, touch_session, record_session_event.".to_string(),
        },
    );

    schema
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schema_has_method_surface() {
        let schema = identity_sled_schema();
        for method in [
            "get_identity",
            "write_identity",
            "provision_container",
            "attach_btrfs_device",
            "touch_session",
            "record_session_event",
            "get_session_history",
        ] {
            assert!(schema.methods.contains_key(method), "missing {method}");
        }
    }

    #[test]
    fn all_subids_are_valid() {
        let raw = serde_json::to_value(schemars::schema_for!(IdentitySledState)).unwrap();
        let mut subids = Vec::new();
        collect_subids(&raw, &mut subids);
        assert!(!subids.is_empty());
        for subid in subids {
            assert!(
                crate::state_plugins::common::oscal::validate_subid(&subid).is_ok(),
                "invalid subid: {subid}"
            );
        }
    }

    fn collect_subids(value: &serde_json::Value, out: &mut Vec<String>) {
        if let Some(obj) = value.as_object() {
            if let Some(subid) = obj.get("x-oscal-subid").and_then(|v| v.as_str()) {
                out.push(subid.to_string());
            }
            for v in obj.values() {
                collect_subids(v, out);
            }
        }
        if let Some(arr) = value.as_array() {
            for v in arr {
                collect_subids(v, out);
            }
        }
    }

    /// VAL-RECORD-001: v3 fields are present on ContainerIdentitySled.
    #[test]
    fn v3_fields_present() {
        let raw = serde_json::to_value(schemars::schema_for!(ContainerIdentitySled)).unwrap();
        let props = raw.get("properties").expect("schema has properties");
        for field in [
            "genesis",
            "arrival_timestamp",
            "chain_head_at_arrival",
            "catalog_hash_at_arrival",
            "head_timestamp_at_arrival",
        ] {
            assert!(
                props.get(field).is_some(),
                "ContainerIdentitySled schema missing v3 field: {field}"
            );
        }
        // hashed_footprint must NOT be a field (replaced by genesis).
        assert!(
            props.get("hashed_footprint").is_none(),
            "hashed_footprint should not be a field on v3 ContainerIdentitySled"
        );
    }

    /// VAL-RECORD-002: Old v2 records with `hashed_footprint` deserialize into
    /// v3 `genesis` field via the serde alias.
    #[test]
    fn v2_backward_compat() {
        let v2_json = serde_json::json!({
            "session_id": "test-session",
            "wireguard_pubkey": "test-pubkey",
            "hashed_footprint": "abc123def456",
            "mutation_index": 5,
            "trace_id": "trace-1",
            "schema_version": 2
        });
        let record: ContainerIdentitySled =
            serde_json::from_value(v2_json).expect("v2 record must deserialize into v3");
        assert_eq!(
            record.genesis,
            Some("abc123def456".to_string()),
            "hashed_footprint must map to genesis via serde alias"
        );
    }

    /// VAL-RECORD-003: hashed_footprint appears only in comments or the serde
    /// alias context, never as a field name on ContainerIdentitySled.
    #[test]
    fn hashed_footprint_only_in_alias() {
        let src = include_str!("identity_sled.rs");
        // Only audit the record-definition region; the tests module itself
        // legitimately names the string in backward-compat assertions.
        let test_start = src.find("#[cfg(test)]").unwrap_or(src.len());
        for (lineno, line) in src[..test_start].lines().enumerate() {
            if line.contains("hashed_footprint") {
                let trimmed = line.trim();
                assert!(
                    trimmed.starts_with("//")
                        || trimmed.starts_with("///")
                        || trimmed.contains("alias = \"hashed_footprint\""),
                    "hashed_footprint at line {} is not in a comment or serde alias: {trimmed}",
                    lineno + 1,
                );
            }
        }
    }

    /// VAL-RECORD-004: RECORD_FORMAT constant is 3.
    #[test]
    fn record_format_is_three() {
        assert_eq!(RECORD_FORMAT, 3u32);
    }

    /// VAL-RECORD-005: SCHEMA_CONTENT_HASH is a stable 64-char hex string.
    #[test]
    fn schema_content_hash_is_stable_hex() {
        assert_eq!(
            SCHEMA_CONTENT_HASH.len(),
            64,
            "SCHEMA_CONTENT_HASH must be 64 hex chars, got {}: {SCHEMA_CONTENT_HASH}",
            SCHEMA_CONTENT_HASH.len()
        );
        assert!(
            SCHEMA_CONTENT_HASH.chars().all(|c| c.is_ascii_hexdigit()),
            "SCHEMA_CONTENT_HASH must be hex: {SCHEMA_CONTENT_HASH}"
        );
    }

    /// VAL-RECORD-005: The hash changes when the struct definition is modified.
    /// This test extracts the struct body (same logic as build.rs), verifies
    /// the hash matches SCHEMA_CONTENT_HASH, then modifies the struct text
    /// and asserts the hash differs.
    #[test]
    fn schema_content_hash_drift() {
        use sha2::{Digest, Sha256};

        let src = include_str!("identity_sled.rs");
        let struct_body = extract_struct_body_test(src, "ContainerIdentitySled")
            .expect("struct definition found");

        // Verify the build-script hash matches the current source.
        let current_hash = hex_encode(&Sha256::digest(struct_body.as_bytes()));
        assert_eq!(
            current_hash, SCHEMA_CONTENT_HASH,
            "SCHEMA_CONTENT_HASH must match the current struct definition"
        );

        // Insert a dummy field before the closing brace to simulate a change.
        let modified = format!(
            "{}    pub __drift_test_field: String,\n}}",
            &struct_body[..struct_body.len() - 1]
        );
        let modified_hash = hex_encode(&Sha256::digest(modified.as_bytes()));
        assert_ne!(
            modified_hash, SCHEMA_CONTENT_HASH,
            "hash must change when a field is added to the struct"
        );
    }

    /// Extract `pub struct <name> { ... }` text, matching build.rs logic.
    fn extract_struct_body_test(src: &str, struct_name: &str) -> Option<String> {
        let needle = format!("pub struct {struct_name} {{");
        let start = src.find(&needle)?;
        let brace_start = src[start..].find('{')? + start;
        let mut depth = 0i32;
        let mut end = brace_start;
        for (i, ch) in src[brace_start..].char_indices() {
            match ch {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        end = brace_start + i + 1;
                        break;
                    }
                }
                _ => {}
            }
        }
        Some(src[start..end].to_string())
    }

    fn hex_encode(bytes: &[u8]) -> String {
        let mut out = String::with_capacity(bytes.len() * 2);
        for &b in bytes {
            out.push_str(&format!("{b:02x}"));
        }
        out
    }
}

// Self-registration: the plugin registry discovers this via inventory
// (single source of the catalog; no central dispatch list).
inventory::submit! {
    crate::default_registry::PluginReg::new("identity_sled", |_ctx| std::sync::Arc::new(IdentitySledPlugin::new()))
}
