//! State plugins - each manages a domain via native protocols
//!
//! These plugins implement the StatePlugin trait from op-state

pub mod dnsresolver;
pub mod full_system;
pub mod keyring;
pub use keyring::KeyringPlugin;
pub mod incus;
pub mod login1;
pub mod lxc;
pub mod mcp;
pub mod net;
pub mod netmaker;
pub mod oci;
pub mod openflow;
pub mod openflow_obfuscation;
pub mod oscal_subid_registry;
pub mod packagekit;
pub mod pcidecl;
// pub mod privacy;
pub mod adc;
pub mod config;
pub mod endpoint;
pub mod gcloud_adc;
pub mod keypair;
pub(crate) mod plugin_schema_defs;
pub mod privacy_router;
pub mod privacy_routes;
pub mod procfs;
pub mod proxy_server;
pub mod s6;
pub mod s6_systemctl;
pub mod service;
pub mod sessdecl;
// pub mod systemd;
// pub mod systemd_networkd;

pub mod agent_config;
pub mod antigravity;
pub mod antigravity_chat;
pub mod btrfs_plugin;
pub mod cognitive_mcp;
pub mod compact_mcp;
pub mod cron;
pub mod factory;
pub mod fail2ban;
pub mod hardware;
pub mod knowledge_plugin;
pub mod mail_server;
pub mod memory_plugin;
pub mod notebooklm;
pub mod ovsdb_bridge;
pub mod ovsdb_daemon;
pub mod proxmox;
pub mod rovs_commands;
pub mod rtnetlink;
pub mod schema_contract;
pub mod schema_renderer;
pub mod software;
pub mod unix_socket;
pub mod users;
pub mod web_ui;
pub mod wgcf;
pub mod wireguard;
pub mod workflows_plugin;
pub mod xray;
pub mod zeroclaw;
pub use antigravity::AntigravityPlugin;
pub use antigravity_chat::AntigravityChatPlugin;
pub use btrfs_plugin::BtrfsPlugin;
pub use cron::CronPlugin;
pub use factory::FactoryPlugin;
pub use fail2ban::Fail2banPlugin;
pub use knowledge_plugin::KnowledgePlugin;
pub use memory_plugin::MemoryPlugin;
pub use notebooklm::NotebookLmPlugin;
pub use schema_renderer::SchemaRendererPlugin;
pub use workflows_plugin::WorkflowsPlugin;

// Re-export plugin types
pub use dnsresolver::DnsResolverPlugin;
pub use full_system::FullSystemPlugin;
pub use incus::IncusPlugin;
pub use login1::Login1Plugin;
pub use lxc::LxcPlugin;
pub use mcp::McpStatePlugin;
pub use mcp::{ExecutionResult, ToolDefinition};
pub use net::NetStatePlugin;
pub use netmaker::{NetmakerConfig, NetmakerPlugin};
pub use oci::OciPlugin;
pub use openflow::OpenFlowPlugin;
pub use openflow_obfuscation::OpenFlowObfuscationPlugin;
pub use oscal_subid_registry::OscalSubidRegistryPlugin;
pub use packagekit::PackageKitPlugin;
pub use pcidecl::PciDeclPlugin;
// pub use privacy::PrivacyPlugin;
pub use adc::AdcPlugin;
pub use agent_config::AgentConfigPlugin;
pub use cognitive_mcp::CognitiveMcpPlugin;
pub use compact_mcp::CompactMcpPlugin;
pub use config::ConfigPlugin;
pub use endpoint::EndpointPlugin;
pub use gcloud_adc::GcloudAdcPlugin;
pub use hardware::HardwarePlugin;
pub use keypair::KeypairPlugin;
pub use ovsdb_bridge::OvsBridgePlugin;
pub use ovsdb_daemon::OvsdbDaemonPlugin;
pub use privacy_router::PrivacyRouterPlugin;
pub use privacy_routes::PrivacyRoutesPlugin;
pub use procfs::ProcfsPlugin;
pub use rovs_commands::RovsCommandsPlugin;
// pub use netmaker::NetmakerPlugin;
pub use proxmox::ProxmoxPlugin;
pub use proxy_server::ProxyServerPlugin;
pub use rtnetlink::RtnetlinkPlugin;
pub use s6::S6StatePlugin;
pub use s6_systemctl::S6SystemctlPlugin;
pub use service::ServicePlugin;
pub use sessdecl::SessDeclPlugin;
pub use software::SoftwarePlugin;
// pub use systemd::SystemdStatePlugin;
pub use mail_server::MailServerPlugin;
pub use unix_socket::UnixSocketPlugin;
pub use users::UsersPlugin;
pub use web_ui::WebUiPlugin;
pub use wgcf::WgcfPlugin;
pub use wireguard::WireGuardPlugin;
pub use xray::XrayPlugin;
pub use zeroclaw::ZeroclawPlugin;
// pub use systemd_networkd::SystemdNetworkdPlugin; // TODO: Plugin not yet implemented

pub mod ctl_plane_chatbot;
pub use ctl_plane_chatbot::CtlPlaneChatbotPlugin;

pub mod freedesktop;
pub use freedesktop::FreeDesktopPlugin;
