// AUTO-GENERATED by schemafy from schemas/openflow/openflow15.json.
// DO NOT EDIT — regenerate with:
//   cargo expand -p op-plugins --bin openflow_schema_gen > /tmp/expanded.rs
//   # then extract the types (this file)
// The schemafy dependency is only needed for regeneration, not for building.
// Post-generation fixup: JsonSchema derive added for plugin schema sealing.

#![allow(non_camel_case_types, non_snake_case)]

use serde::{Serialize, Deserialize};
use schemars::JsonSchema;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct Action {
    /// Encap ether type (for OFPAT_ENCAP), e.g. ethernet=1
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ether_type: Option<String>,
    /// EtherType (for OFPAT_PUSH_VLAN / OFPAT_PUSH_MPLS)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ethertype: Option<i64>,
    /// Experimenter data as hex (for OFPAT_EXPERIMENTER)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub experimenter_data: Option<String>,
    /// Experimenter ID (for OFPAT_EXPERIMENTER)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub experimenter_id: Option<i64>,
    /// Field name (for OFPAT_SET_FIELD), e.g. eth_dst, nw_src, vlan_vid
    #[serde(skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    /// Group ID (for OFPAT_GROUP)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub group_id: Option<i64>,
    /// MPLS TTL (for OFPAT_SET_MPLS_TTL)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mpls_ttl: Option<i64>,
    /// Network TTL (for OFPAT_SET_NW_TTL)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nw_ttl: Option<i64>,
    /// Output port name or number (for OFPAT_OUTPUT). Special: LOCAL, NORMAL, FLOOD, ALL, IN_PORT,
    /// CONTROLLER, ANY
    #[serde(skip_serializing_if = "Option::is_none")]
    pub port: Option<String>,
    /// Queue ID (for OFPAT_SET_QUEUE)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub queue_id: Option<i64>,
    #[serde(rename = "type")]
    pub type_: ActionType,
    /// Field value (for OFPAT_SET_FIELD)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(rename = "action_type")]
pub enum ActionType {
    #[serde(rename = "OFPAT_OUTPUT")]
    OfpatOutput,
    #[serde(rename = "OFPAT_COPY_TTL_OUT")]
    OfpatCopyTtlOut,
    #[serde(rename = "OFPAT_COPY_TTL_IN")]
    OfpatCopyTtlIn,
    #[serde(rename = "OFPAT_SET_MPLS_TTL")]
    OfpatSetMplsTtl,
    #[serde(rename = "OFPAT_DEC_MPLS_TTL")]
    OfpatDecMplsTtl,
    #[serde(rename = "OFPAT_PUSH_VLAN")]
    OfpatPushVlan,
    #[serde(rename = "OFPAT_POP_VLAN")]
    OfpatPopVlan,
    #[serde(rename = "OFPAT_PUSH_MPLS")]
    OfpatPushMpls,
    #[serde(rename = "OFPAT_POP_MPLS")]
    OfpatPopMpls,
    #[serde(rename = "OFPAT_SET_QUEUE")]
    OfpatSetQueue,
    #[serde(rename = "OFPAT_GROUP")]
    OfpatGroup,
    #[serde(rename = "OFPAT_SET_NW_TTL")]
    OfpatSetNwTtl,
    #[serde(rename = "OFPAT_DEC_NW_TTL")]
    OfpatDecNwTtl,
    #[serde(rename = "OFPAT_SET_FIELD")]
    OfpatSetField,
    #[serde(rename = "OFPAT_PUSH_PBB")]
    OfpatPushPbb,
    #[serde(rename = "OFPAT_POP_PBB")]
    OfpatPopPbb,
    #[serde(rename = "OFPAT_ENCAP")]
    OfpatEncap,
    #[serde(rename = "OFPAT_DECAP")]
    OfpatDecap,
    #[serde(rename = "OFPAT_EXPERIMENTER")]
    OfpatExperimenter,
}
/// Arbitrary data as hex string
pub type Data = String;
/// Ethernet address (MAC)
pub type Ethernet = String;
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(rename = "flow_mod_command")]
pub enum FlowModCommand {
    #[serde(rename = "OFPFC_ADD")]
    OfpfcAdd,
    #[serde(rename = "OFPFC_MODIFY")]
    OfpfcModify,
    #[serde(rename = "OFPFC_MODIFY_STRICT")]
    OfpfcModifyStrict,
    #[serde(rename = "OFPFC_DELETE")]
    OfpfcDelete,
    #[serde(rename = "OFPFC_DELETE_STRICT")]
    OfpfcDeleteStrict,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(rename = "flow_mod_flag")]
pub enum FlowModFlag {
    #[serde(rename = "OFPFF_SEND_FLOW_REM")]
    OfpffSendFlowRem,
    #[serde(rename = "OFPFF_CHECK_OVERLAP")]
    OfpffCheckOverlap,
    #[serde(rename = "OFPFF_RESET_COUNTS")]
    OfpffResetCounts,
    #[serde(rename = "OFPFF_NO_PKT_COUNTS")]
    OfpffNoPktCounts,
    #[serde(rename = "OFPFF_NO_BYT_COUNTS")]
    OfpffNoBytCounts,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(rename = "ofp_flow_mod")]
pub struct OfpFlowMod {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actions: Option<Vec<Action>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub buffer_id: Option<i64>,
    pub command: FlowModCommand,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cookie: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cookie_mask: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flags: Option<Vec<FlowModFlag>>,
    pub hard_timeout: i64,
    pub idle_timeout: i64,
    #[serde(rename = "match")]
    pub match_: OfpMatch,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub out_group: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub out_port: Option<i64>,
    pub priority: i64,
    pub table_id: i64,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(rename = "ofp_match")]
pub struct OfpMatch {
    pub length: i64,
    pub match_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oxm_fields: Option<Vec<OxmField>>,
}
/// Optional data as hex string
pub type OptionalData = String;
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(rename = "oxm_class")]
pub enum OxmClass {
    #[serde(rename = "OFPXMC_NXM_0")]
    OfpxmcNxm0,
    #[serde(rename = "OFPXMC_NXM_1")]
    OfpxmcNxm1,
    #[serde(rename = "OFPXMC_OPENFLOW_BASIC")]
    OfpxmcOpenflowBasic,
    #[serde(rename = "OFPXMC_EXPERIMENTER")]
    OfpxmcExperimenter,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(rename = "oxm_field")]
pub struct OxmField {
    pub oxm_class: OxmClass,
    pub oxm_field: OxmFieldType,
    pub oxm_hasmask: bool,
    pub oxm_length: i64,
    /// Optional mask (hex string)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oxm_mask: Option<String>,
    /// Field value (hex string or decimal for simple integers)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oxm_value: Option<String>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(rename = "oxm_field_type")]
pub enum OxmFieldType {
    #[serde(rename = "OFPXMT_OFB_IN_PORT")]
    OfpxmtOfbInPort,
    #[serde(rename = "OFPXMT_OFB_IN_PHY_PORT")]
    OfpxmtOfbInPhyPort,
    #[serde(rename = "OFPXMT_OFB_METADATA")]
    OfpxmtOfbMetadata,
    #[serde(rename = "OFPXMT_OFB_ETH_DST")]
    OfpxmtOfbEthDst,
    #[serde(rename = "OFPXMT_OFB_ETH_SRC")]
    OfpxmtOfbEthSrc,
    #[serde(rename = "OFPXMT_OFB_ETH_TYPE")]
    OfpxmtOfbEthType,
    #[serde(rename = "OFPXMT_OFB_VLAN_VID")]
    OfpxmtOfbVlanVid,
    #[serde(rename = "OFPXMT_OFB_VLAN_PCP")]
    OfpxmtOfbVlanPcp,
    #[serde(rename = "OFPXMT_OFB_IP_DSCP")]
    OfpxmtOfbIpDscp,
    #[serde(rename = "OFPXMT_OFB_IP_ECN")]
    OfpxmtOfbIpEcn,
    #[serde(rename = "OFPXMT_OFB_IP_PROTO")]
    OfpxmtOfbIpProto,
    #[serde(rename = "OFPXMT_OFB_IPV4_SRC")]
    OfpxmtOfbIpv4Src,
    #[serde(rename = "OFPXMT_OFB_IPV4_DST")]
    OfpxmtOfbIpv4Dst,
    #[serde(rename = "OFPXMT_OFB_TCP_SRC")]
    OfpxmtOfbTcpSrc,
    #[serde(rename = "OFPXMT_OFB_TCP_DST")]
    OfpxmtOfbTcpDst,
    #[serde(rename = "OFPXMT_OFB_UDP_SRC")]
    OfpxmtOfbUdpSrc,
    #[serde(rename = "OFPXMT_OFB_UDP_DST")]
    OfpxmtOfbUdpDst,
    #[serde(rename = "OFPXMT_OFB_SCTP_SRC")]
    OfpxmtOfbSctpSrc,
    #[serde(rename = "OFPXMT_OFB_SCTP_DST")]
    OfpxmtOfbSctpDst,
    #[serde(rename = "OFPXMT_OFB_ICMPV4_TYPE")]
    OfpxmtOfbIcmpv4Type,
    #[serde(rename = "OFPXMT_OFB_ICMPV4_CODE")]
    OfpxmtOfbIcmpv4Code,
    #[serde(rename = "OFPXMT_OFB_ARP_OP")]
    OfpxmtOfbArpOp,
    #[serde(rename = "OFPXMT_OFB_ARP_SPA")]
    OfpxmtOfbArpSpa,
    #[serde(rename = "OFPXMT_OFB_ARP_TPA")]
    OfpxmtOfbArpTpa,
    #[serde(rename = "OFPXMT_OFB_ARP_SHA")]
    OfpxmtOfbArpSha,
    #[serde(rename = "OFPXMT_OFB_ARP_THA")]
    OfpxmtOfbArpTha,
    #[serde(rename = "OFPXMT_OFB_IPV6_SRC")]
    OfpxmtOfbIpv6Src,
    #[serde(rename = "OFPXMT_OFB_IPV6_DST")]
    OfpxmtOfbIpv6Dst,
    #[serde(rename = "OFPXMT_OFB_IPV6_FLABEL")]
    OfpxmtOfbIpv6Flabel,
    #[serde(rename = "OFPXMT_OFB_ICMPV6_TYPE")]
    OfpxmtOfbIcmpv6Type,
    #[serde(rename = "OFPXMT_OFB_ICMPV6_CODE")]
    OfpxmtOfbIcmpv6Code,
    #[serde(rename = "OFPXMT_OFB_IPV6_ND_TARGET")]
    OfpxmtOfbIpv6NdTarget,
    #[serde(rename = "OFPXMT_OFB_IPV6_ND_SLL")]
    OfpxmtOfbIpv6NdSll,
    #[serde(rename = "OFPXMT_OFB_IPV6_ND_TLL")]
    OfpxmtOfbIpv6NdTll,
    #[serde(rename = "OFPXMT_OFB_MPLS_LABEL")]
    OfpxmtOfbMplsLabel,
    #[serde(rename = "OFPXMT_OFB_MPLS_TC")]
    OfpxmtOfbMplsTc,
    #[serde(rename = "OFPXMT_OFB_MPLS_BOS")]
    OfpxmtOfbMplsBos,
    #[serde(rename = "OFPXMT_OFB_PBB_ISID")]
    OfpxmtOfbPbbIsid,
    #[serde(rename = "OFPXMT_OFB_TUNNEL_ID")]
    OfpxmtOfbTunnelId,
    #[serde(rename = "OFPXMT_OFB_IPV6_EXTHDR")]
    OfpxmtOfbIpv6Exthdr,
    #[serde(rename = "OFPXMT_OFB_PACKET_TYPE")]
    OfpxmtOfbPacketType,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct OpenFlowFlowModInput {
    /// Bridge name
    pub bridge: String,
    pub flow_mod: OfpFlowMod,
}

