//! GENERATED by `cargo run -p op-plugins --bin gen_tched_router_config_surface`.
//! DO NOT EDIT — regenerate after bumping the `zeroclaw` dependency.
//!
//! Complete 3tched Router config surface: every upstream config section
//! as a real-typed `Get<Section>Config` method, plus `GetConfig` (full,
//! secret-masked) and `PatchConfig` (validated mutation). Local 3tched
//! Router configuration structs are plain config sections here — there
//! is no separate "configurable options" projection. No cache, no
//! projection: reads parse the current config; mutations land in state.

use super::common::errors::TchedRouterError;
use super::plugin_scaffold_helpers::method_decl_from_schemars_with_output;
use super::tched_router::{DispatchOutcome, TchedRouterState};
use op_state_store::{CapabilityDecl, PluginSchema, SideEffect};
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;

/// Empty input for config read methods.
#[derive(Debug, Clone, Default, Serialize, Deserialize, schemars::JsonSchema)]
pub struct ConfigMethodInput {}

/// Output for `GetConfig` — the full upstream configuration, typed by
/// the real `zeroclaw::Config`. Secrets are masked by dispatch.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.config.result@v1"))]
pub struct GetConfigOutput {
    /// Full upstream configuration.
    pub config: zeroclaw::Config,
}

/// Input for `PatchConfig`: replace one config section.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct PatchConfigInput {
    /// Section key (e.g. `gateway`, `memory`, `channels_config`).
    pub section: String,
    /// New section value; validated against the real upstream type.
    pub value: JsonValue,
}

/// Output for `PatchConfig` — the validated value that was applied.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
pub struct PatchConfigOutput {
    /// Section that was patched.
    pub section: String,
    /// Validated value now in effect.
    pub value: JsonValue,
}

/// Output for `GetAgentConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.agent-config.result@v1"))]
pub struct GetAgentConfigOutput {
    /// Current `agent` configuration.
    pub config: zeroclaw::config::AgentConfig,
}

/// Output for `GetAgentsConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.agents-config.result@v1"))]
pub struct GetAgentsConfigOutput {
    /// Current `agents` configuration.
    pub config: std::collections::HashMap<String, zeroclaw::config::DelegateAgentConfig>,
}

/// Output for `GetAutonomyConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.autonomy-config.result@v1"))]
pub struct GetAutonomyConfigOutput {
    /// Current `autonomy` configuration.
    pub config: zeroclaw::config::AutonomyConfig,
}

/// Output for `GetBackupConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.backup-config.result@v1"))]
pub struct GetBackupConfigOutput {
    /// Current `backup` configuration.
    pub config: zeroclaw::config::BackupConfig,
}

/// Output for `GetBrowserConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.browser-config.result@v1"))]
pub struct GetBrowserConfigOutput {
    /// Current `browser` configuration.
    pub config: zeroclaw::config::BrowserConfig,
}

/// Output for `GetBrowserDelegateConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.browser-delegate-config.result@v1"))]
pub struct GetBrowserDelegateConfigOutput {
    /// Current `browser_delegate` configuration.
    pub config: zeroclaw::tools::browser_delegate::BrowserDelegateConfig,
}

/// Output for `GetChannelsConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.channels-config-config.result@v1"))]
pub struct GetChannelsConfigOutput {
    /// Current `channels_config` configuration.
    pub config: zeroclaw::config::ChannelsConfig,
}

/// Output for `GetCloudOpsConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.cloud-ops-config.result@v1"))]
pub struct GetCloudOpsConfigOutput {
    /// Current `cloud_ops` configuration.
    pub config: zeroclaw::config::CloudOpsConfig,
}

/// Output for `GetComposioConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.composio-config.result@v1"))]
pub struct GetComposioConfigOutput {
    /// Current `composio` configuration.
    pub config: zeroclaw::config::ComposioConfig,
}

/// Output for `GetConversationalAiConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.conversational-ai-config.result@v1"))]
pub struct GetConversationalAiConfigOutput {
    /// Current `conversational_ai` configuration.
    pub config: zeroclaw::config::ConversationalAiConfig,
}

/// Output for `GetCostConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.cost-config.result@v1"))]
pub struct GetCostConfigOutput {
    /// Current `cost` configuration.
    pub config: zeroclaw::config::CostConfig,
}

/// Output for `GetCronConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.cron-config.result@v1"))]
pub struct GetCronConfigOutput {
    /// Current `cron` configuration.
    pub config: zeroclaw::config::CronConfig,
}

/// Output for `GetDataRetentionConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.data-retention-config.result@v1"))]
pub struct GetDataRetentionConfigOutput {
    /// Current `data_retention` configuration.
    pub config: zeroclaw::config::DataRetentionConfig,
}

/// Output for `GetDelegateConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.delegate-config.result@v1"))]
pub struct GetDelegateConfigOutput {
    /// Current `delegate` configuration.
    pub config: zeroclaw::config::DelegateToolConfig,
}

/// Output for `GetEmbeddingRoutesConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.embedding-routes-config.result@v1"))]
pub struct GetEmbeddingRoutesConfigOutput {
    /// Current `embedding_routes` configuration.
    pub config: Vec<zeroclaw::config::EmbeddingRouteConfig>,
}

/// Output for `GetExtraHeadersConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.extra-headers-config.result@v1"))]
pub struct GetExtraHeadersConfigOutput {
    /// Current `extra_headers` configuration.
    pub config: std::collections::HashMap<String, String>,
}

/// Output for `GetGatewayConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.gateway-config.result@v1"))]
pub struct GetGatewayConfigOutput {
    /// Current `gateway` configuration.
    pub config: zeroclaw::config::GatewayConfig,
}

/// Output for `GetGoogleWorkspaceConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.google-workspace-config.result@v1"))]
pub struct GetGoogleWorkspaceConfigOutput {
    /// Current `google_workspace` configuration.
    pub config: zeroclaw::config::GoogleWorkspaceConfig,
}

/// Output for `GetHardwareConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.hardware-config.result@v1"))]
pub struct GetHardwareConfigOutput {
    /// Current `hardware` configuration.
    pub config: zeroclaw::config::HardwareConfig,
}

/// Output for `GetHeartbeatConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.heartbeat-config.result@v1"))]
pub struct GetHeartbeatConfigOutput {
    /// Current `heartbeat` configuration.
    pub config: zeroclaw::config::HeartbeatConfig,
}

/// Output for `GetHooksConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.hooks-config.result@v1"))]
pub struct GetHooksConfigOutput {
    /// Current `hooks` configuration.
    pub config: zeroclaw::config::HooksConfig,
}

/// Output for `GetHttpRequestConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.http-request-config.result@v1"))]
pub struct GetHttpRequestConfigOutput {
    /// Current `http_request` configuration.
    pub config: zeroclaw::config::HttpRequestConfig,
}

/// Output for `GetIdentityConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.identity-config.result@v1"))]
pub struct GetIdentityConfigOutput {
    /// Current `identity` configuration.
    pub config: zeroclaw::config::IdentityConfig,
}

/// Output for `GetJiraConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.jira-config.result@v1"))]
pub struct GetJiraConfigOutput {
    /// Current `jira` configuration.
    pub config: zeroclaw::config::JiraConfig,
}

/// Output for `GetKnowledgeConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.knowledge-config.result@v1"))]
pub struct GetKnowledgeConfigOutput {
    /// Current `knowledge` configuration.
    pub config: zeroclaw::config::KnowledgeConfig,
}

/// Output for `GetLinkedinConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.linkedin-config.result@v1"))]
pub struct GetLinkedinConfigOutput {
    /// Current `linkedin` configuration.
    pub config: zeroclaw::config::LinkedInConfig,
}

/// Output for `GetMcpConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.mcp-config.result@v1"))]
pub struct GetMcpConfigOutput {
    /// Current `mcp` configuration.
    pub config: zeroclaw::config::McpConfig,
}

/// Output for `GetMemoryConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.memory-config.result@v1"))]
pub struct GetMemoryConfigOutput {
    /// Current `memory` configuration.
    pub config: zeroclaw::config::MemoryConfig,
}

/// Output for `GetMicrosoft365Config`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.microsoft365-config.result@v1"))]
pub struct GetMicrosoft365ConfigOutput {
    /// Current `microsoft365` configuration.
    pub config: zeroclaw::config::Microsoft365Config,
}

/// Output for `GetModelProvidersConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.model-providers-config.result@v1"))]
pub struct GetModelProvidersConfigOutput {
    /// Current `model_providers` configuration.
    pub config: std::collections::HashMap<String, zeroclaw::config::schema::ModelProviderConfig>,
}

/// Output for `GetModelRoutesConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.model-routes-config.result@v1"))]
pub struct GetModelRoutesConfigOutput {
    /// Current `model_routes` configuration.
    pub config: Vec<zeroclaw::config::ModelRouteConfig>,
}

/// Output for `GetMultimodalConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.multimodal-config.result@v1"))]
pub struct GetMultimodalConfigOutput {
    /// Current `multimodal` configuration.
    pub config: zeroclaw::config::MultimodalConfig,
}

/// Output for `GetNodeTransportConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.node-transport-config.result@v1"))]
pub struct GetNodeTransportConfigOutput {
    /// Current `node_transport` configuration.
    pub config: zeroclaw::config::NodeTransportConfig,
}

/// Output for `GetNodesConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.nodes-config.result@v1"))]
pub struct GetNodesConfigOutput {
    /// Current `nodes` configuration.
    pub config: zeroclaw::config::NodesConfig,
}

/// Output for `GetNotionConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.notion-config.result@v1"))]
pub struct GetNotionConfigOutput {
    /// Current `notion` configuration.
    pub config: zeroclaw::config::NotionConfig,
}

/// Output for `GetObservabilityConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.observability-config.result@v1"))]
pub struct GetObservabilityConfigOutput {
    /// Current `observability` configuration.
    pub config: zeroclaw::config::ObservabilityConfig,
}

/// Output for `GetPeripheralsConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.peripherals-config.result@v1"))]
pub struct GetPeripheralsConfigOutput {
    /// Current `peripherals` configuration.
    pub config: zeroclaw::config::PeripheralsConfig,
}

/// Output for `GetPluginsConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.plugins-config.result@v1"))]
pub struct GetPluginsConfigOutput {
    /// Current `plugins` configuration.
    pub config: zeroclaw::config::PluginsConfig,
}

/// Output for `GetProjectIntelConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.project-intel-config.result@v1"))]
pub struct GetProjectIntelConfigOutput {
    /// Current `project_intel` configuration.
    pub config: zeroclaw::config::ProjectIntelConfig,
}

/// Output for `GetProxyConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.proxy-config.result@v1"))]
pub struct GetProxyConfigOutput {
    /// Current `proxy` configuration.
    pub config: zeroclaw::config::ProxyConfig,
}

/// Output for `GetQueryClassificationConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.query-classification-config.result@v1"))]
pub struct GetQueryClassificationConfigOutput {
    /// Current `query_classification` configuration.
    pub config: zeroclaw::config::QueryClassificationConfig,
}

/// Output for `GetReliabilityConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.reliability-config.result@v1"))]
pub struct GetReliabilityConfigOutput {
    /// Current `reliability` configuration.
    pub config: zeroclaw::config::ReliabilityConfig,
}

/// Output for `GetRuntimeConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.runtime-config.result@v1"))]
pub struct GetRuntimeConfigOutput {
    /// Current `runtime` configuration.
    pub config: zeroclaw::config::RuntimeConfig,
}

/// Output for `GetSchedulerConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.scheduler-config.result@v1"))]
pub struct GetSchedulerConfigOutput {
    /// Current `scheduler` configuration.
    pub config: zeroclaw::config::SchedulerConfig,
}

/// Output for `GetSecretsConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.secrets-config.result@v1"))]
pub struct GetSecretsConfigOutput {
    /// Current `secrets` configuration.
    pub config: zeroclaw::config::SecretsConfig,
}

/// Output for `GetSecurityConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.security-config.result@v1"))]
pub struct GetSecurityConfigOutput {
    /// Current `security` configuration.
    pub config: zeroclaw::config::SecurityConfig,
}

/// Output for `GetSecurityOpsConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.security-ops-config.result@v1"))]
pub struct GetSecurityOpsConfigOutput {
    /// Current `security_ops` configuration.
    pub config: zeroclaw::config::SecurityOpsConfig,
}

/// Output for `GetSkillsConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.skills-config.result@v1"))]
pub struct GetSkillsConfigOutput {
    /// Current `skills` configuration.
    pub config: zeroclaw::config::SkillsConfig,
}

/// Output for `GetStorageConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.storage-config.result@v1"))]
pub struct GetStorageConfigOutput {
    /// Current `storage` configuration.
    pub config: zeroclaw::config::StorageConfig,
}

/// Output for `GetSwarmsConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.swarms-config.result@v1"))]
pub struct GetSwarmsConfigOutput {
    /// Current `swarms` configuration.
    pub config: std::collections::HashMap<String, zeroclaw::config::SwarmConfig>,
}

/// Output for `GetTextBrowserConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.text-browser-config.result@v1"))]
pub struct GetTextBrowserConfigOutput {
    /// Current `text_browser` configuration.
    pub config: zeroclaw::config::TextBrowserConfig,
}

/// Output for `GetTranscriptionConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.transcription-config.result@v1"))]
pub struct GetTranscriptionConfigOutput {
    /// Current `transcription` configuration.
    pub config: zeroclaw::config::TranscriptionConfig,
}

/// Output for `GetTtsConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.tts-config.result@v1"))]
pub struct GetTtsConfigOutput {
    /// Current `tts` configuration.
    pub config: zeroclaw::config::TtsConfig,
}

/// Output for `GetTunnelConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.tunnel-config.result@v1"))]
pub struct GetTunnelConfigOutput {
    /// Current `tunnel` configuration.
    pub config: zeroclaw::config::TunnelConfig,
}

/// Output for `GetWebFetchConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.web-fetch-config.result@v1"))]
pub struct GetWebFetchConfigOutput {
    /// Current `web_fetch` configuration.
    pub config: zeroclaw::config::WebFetchConfig,
}

/// Output for `GetWebSearchConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.web-search-config.result@v1"))]
pub struct GetWebSearchConfigOutput {
    /// Current `web_search` configuration.
    pub config: zeroclaw::config::WebSearchConfig,
}

/// Output for `GetWorkspaceConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.workspace-config.result@v1"))]
pub struct GetWorkspaceConfigOutput {
    /// Current `workspace` configuration.
    pub config: zeroclaw::config::WorkspaceConfig,
}

/// Output for `GetModelAssignmentsConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.model-assignments-config.result@v1"))]
pub struct GetModelAssignmentsConfigOutput {
    /// Current `model_assignments` configuration.
    pub config: super::tched_router::ModelAssignments,
}

/// Output for `GetMemoryNamespacesConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.memory-namespaces-config.result@v1"))]
pub struct GetMemoryNamespacesConfigOutput {
    /// Current `memory_namespaces` configuration.
    pub config: Vec<super::tched_router::MemoryNamespaceOption>,
}

/// Output for `GetRegistrationServiceConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.registration-service-config.result@v1"))]
pub struct GetRegistrationServiceConfigOutput {
    /// Current `registration_service` configuration.
    pub config: super::tched_router::RegistrationServiceSchema,
}

/// Output for `GetUserContainerConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.user-container-config.result@v1"))]
pub struct GetUserContainerConfigOutput {
    /// Current `user_container` configuration.
    pub config: super::tched_router::UserContainerOptions,
}

/// Output for `GetIdentityChainConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.identity-chain-config.result@v1"))]
pub struct GetIdentityChainConfigOutput {
    /// Current `identity_chain` configuration.
    pub config: super::tched_router::IdentityOptions,
}

/// Output for `GetPrivacyPolicyConfig`.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(extend("x-oscal-subid" = "exp.service.3tched-router.privacy-policy-config.result@v1"))]
pub struct GetPrivacyPolicyConfigOutput {
    /// Current `privacy_policy` configuration.
    pub config: super::tched_router::PrivacyOptions,
}

/// (method, section key, source) for every config read.
pub const SECTIONS: &[(&str, &str, SectionSource)] = &[
    ("GetAgentConfig", "agent", SectionSource::Upstream),
    ("GetAgentsConfig", "agents", SectionSource::Upstream),
    ("GetAutonomyConfig", "autonomy", SectionSource::Upstream),
    ("GetBackupConfig", "backup", SectionSource::Upstream),
    ("GetBrowserConfig", "browser", SectionSource::Upstream),
    (
        "GetBrowserDelegateConfig",
        "browser_delegate",
        SectionSource::Upstream,
    ),
    (
        "GetChannelsConfig",
        "channels_config",
        SectionSource::Upstream,
    ),
    ("GetCloudOpsConfig", "cloud_ops", SectionSource::Upstream),
    ("GetComposioConfig", "composio", SectionSource::Upstream),
    (
        "GetConversationalAiConfig",
        "conversational_ai",
        SectionSource::Upstream,
    ),
    ("GetCostConfig", "cost", SectionSource::Upstream),
    ("GetCronConfig", "cron", SectionSource::Upstream),
    (
        "GetDataRetentionConfig",
        "data_retention",
        SectionSource::Upstream,
    ),
    ("GetDelegateConfig", "delegate", SectionSource::Upstream),
    (
        "GetEmbeddingRoutesConfig",
        "embedding_routes",
        SectionSource::Upstream,
    ),
    (
        "GetExtraHeadersConfig",
        "extra_headers",
        SectionSource::Upstream,
    ),
    ("GetGatewayConfig", "gateway", SectionSource::Upstream),
    (
        "GetGoogleWorkspaceConfig",
        "google_workspace",
        SectionSource::Upstream,
    ),
    ("GetHardwareConfig", "hardware", SectionSource::Upstream),
    ("GetHeartbeatConfig", "heartbeat", SectionSource::Upstream),
    ("GetHooksConfig", "hooks", SectionSource::Upstream),
    (
        "GetHttpRequestConfig",
        "http_request",
        SectionSource::Upstream,
    ),
    ("GetIdentityConfig", "identity", SectionSource::Upstream),
    ("GetJiraConfig", "jira", SectionSource::Upstream),
    ("GetKnowledgeConfig", "knowledge", SectionSource::Upstream),
    ("GetLinkedinConfig", "linkedin", SectionSource::Upstream),
    ("GetMcpConfig", "mcp", SectionSource::Upstream),
    ("GetMemoryConfig", "memory", SectionSource::Upstream),
    (
        "GetMicrosoft365Config",
        "microsoft365",
        SectionSource::Upstream,
    ),
    (
        "GetModelProvidersConfig",
        "model_providers",
        SectionSource::Upstream,
    ),
    (
        "GetModelRoutesConfig",
        "model_routes",
        SectionSource::Upstream,
    ),
    ("GetMultimodalConfig", "multimodal", SectionSource::Upstream),
    (
        "GetNodeTransportConfig",
        "node_transport",
        SectionSource::Upstream,
    ),
    ("GetNodesConfig", "nodes", SectionSource::Upstream),
    ("GetNotionConfig", "notion", SectionSource::Upstream),
    (
        "GetObservabilityConfig",
        "observability",
        SectionSource::Upstream,
    ),
    (
        "GetPeripheralsConfig",
        "peripherals",
        SectionSource::Upstream,
    ),
    ("GetPluginsConfig", "plugins", SectionSource::Upstream),
    (
        "GetProjectIntelConfig",
        "project_intel",
        SectionSource::Upstream,
    ),
    ("GetProxyConfig", "proxy", SectionSource::Upstream),
    (
        "GetQueryClassificationConfig",
        "query_classification",
        SectionSource::Upstream,
    ),
    (
        "GetReliabilityConfig",
        "reliability",
        SectionSource::Upstream,
    ),
    ("GetRuntimeConfig", "runtime", SectionSource::Upstream),
    ("GetSchedulerConfig", "scheduler", SectionSource::Upstream),
    ("GetSecretsConfig", "secrets", SectionSource::Upstream),
    ("GetSecurityConfig", "security", SectionSource::Upstream),
    (
        "GetSecurityOpsConfig",
        "security_ops",
        SectionSource::Upstream,
    ),
    ("GetSkillsConfig", "skills", SectionSource::Upstream),
    ("GetStorageConfig", "storage", SectionSource::Upstream),
    ("GetSwarmsConfig", "swarms", SectionSource::Upstream),
    (
        "GetTextBrowserConfig",
        "text_browser",
        SectionSource::Upstream,
    ),
    (
        "GetTranscriptionConfig",
        "transcription",
        SectionSource::Upstream,
    ),
    ("GetTtsConfig", "tts", SectionSource::Upstream),
    ("GetTunnelConfig", "tunnel", SectionSource::Upstream),
    ("GetWebFetchConfig", "web_fetch", SectionSource::Upstream),
    ("GetWebSearchConfig", "web_search", SectionSource::Upstream),
    ("GetWorkspaceConfig", "workspace", SectionSource::Upstream),
    (
        "GetModelAssignmentsConfig",
        "model_assignments",
        SectionSource::Local,
    ),
    (
        "GetMemoryNamespacesConfig",
        "memory_namespaces",
        SectionSource::Local,
    ),
    (
        "GetRegistrationServiceConfig",
        "registration_service",
        SectionSource::Local,
    ),
    (
        "GetUserContainerConfig",
        "user_container",
        SectionSource::Local,
    ),
    (
        "GetIdentityChainConfig",
        "identity_chain",
        SectionSource::Local,
    ),
    (
        "GetPrivacyPolicyConfig",
        "privacy_policy",
        SectionSource::Local,
    ),
];

/// Where a config section is read from.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SectionSource {
    /// Upstream `zeroclaw::Config` (the config file).
    Upstream,
    /// Local 3tched Router state (a plain configuration).
    Local,
}

/// Every method owned by this surface (for dispatch membership checks).
pub const CONFIG_METHODS: &[&str] = &[
    "GetConfig",
    "PatchConfig",
    "GetAgentConfig",
    "GetAgentsConfig",
    "GetAutonomyConfig",
    "GetBackupConfig",
    "GetBrowserConfig",
    "GetBrowserDelegateConfig",
    "GetChannelsConfig",
    "GetCloudOpsConfig",
    "GetComposioConfig",
    "GetConversationalAiConfig",
    "GetCostConfig",
    "GetCronConfig",
    "GetDataRetentionConfig",
    "GetDelegateConfig",
    "GetEmbeddingRoutesConfig",
    "GetExtraHeadersConfig",
    "GetGatewayConfig",
    "GetGoogleWorkspaceConfig",
    "GetHardwareConfig",
    "GetHeartbeatConfig",
    "GetHooksConfig",
    "GetHttpRequestConfig",
    "GetIdentityConfig",
    "GetJiraConfig",
    "GetKnowledgeConfig",
    "GetLinkedinConfig",
    "GetMcpConfig",
    "GetMemoryConfig",
    "GetMicrosoft365Config",
    "GetModelProvidersConfig",
    "GetModelRoutesConfig",
    "GetMultimodalConfig",
    "GetNodeTransportConfig",
    "GetNodesConfig",
    "GetNotionConfig",
    "GetObservabilityConfig",
    "GetPeripheralsConfig",
    "GetPluginsConfig",
    "GetProjectIntelConfig",
    "GetProxyConfig",
    "GetQueryClassificationConfig",
    "GetReliabilityConfig",
    "GetRuntimeConfig",
    "GetSchedulerConfig",
    "GetSecretsConfig",
    "GetSecurityConfig",
    "GetSecurityOpsConfig",
    "GetSkillsConfig",
    "GetStorageConfig",
    "GetSwarmsConfig",
    "GetTextBrowserConfig",
    "GetTranscriptionConfig",
    "GetTtsConfig",
    "GetTunnelConfig",
    "GetWebFetchConfig",
    "GetWebSearchConfig",
    "GetWorkspaceConfig",
    "GetModelAssignmentsConfig",
    "GetMemoryNamespacesConfig",
    "GetRegistrationServiceConfig",
    "GetUserContainerConfig",
    "GetIdentityChainConfig",
    "GetPrivacyPolicyConfig",
];

/// Register every config method and its declared capability on the schema.
///
/// The plugin is the single declaration point: each method's
/// `required_capability` has a matching `schema.capabilities` entry
/// (closure-clean under `validate_capability_closure`).
pub fn register_config_methods(schema: &mut PluginSchema) {
    schema.methods.insert(
        "GetConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetConfigOutput>(
            "GetConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.config.read@v1",
            "obs.service.3tched-router.config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.config.read@v1".to_string(),
            description: "Read the full 3tched Router configuration (secrets masked).".to_string(),
        },
    );
    schema.methods.insert(
        "PatchConfig".to_string(),
        method_decl_from_schemars_with_output::<PatchConfigInput, PatchConfigOutput>(
            "PatchConfig",
            SideEffect::Mutation,
            false,
            "cap.software.3tched-router.config.write@v1",
            "mut.service.3tched-router.config.patch@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.config.write@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.config.write@v1".to_string(),
            description: "Patch 3tched Router configuration sections (validated).".to_string(),
        },
    );
    schema.methods.insert(
        "GetAgentConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetAgentConfigOutput>(
            "GetAgentConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.agent-config.read@v1",
            "obs.service.3tched-router.agent-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.agent-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.agent-config.read@v1".to_string(),
            description: "Read the 3tched Router `agent` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetAgentsConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetAgentsConfigOutput>(
            "GetAgentsConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.agents-config.read@v1",
            "obs.service.3tched-router.agents-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.agents-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.agents-config.read@v1".to_string(),
            description: "Read the 3tched Router `agents` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetAutonomyConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetAutonomyConfigOutput>(
            "GetAutonomyConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.autonomy-config.read@v1",
            "obs.service.3tched-router.autonomy-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.autonomy-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.autonomy-config.read@v1".to_string(),
            description: "Read the 3tched Router `autonomy` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetBackupConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetBackupConfigOutput>(
            "GetBackupConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.backup-config.read@v1",
            "obs.service.3tched-router.backup-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.backup-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.backup-config.read@v1".to_string(),
            description: "Read the 3tched Router `backup` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetBrowserConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetBrowserConfigOutput>(
            "GetBrowserConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.browser-config.read@v1",
            "obs.service.3tched-router.browser-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.browser-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.browser-config.read@v1".to_string(),
            description: "Read the 3tched Router `browser` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetBrowserDelegateConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetBrowserDelegateConfigOutput>(
            "GetBrowserDelegateConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.browser-delegate-config.read@v1",
            "obs.service.3tched-router.browser-delegate-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.browser-delegate-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.browser-delegate-config.read@v1".to_string(),
            description: "Read the 3tched Router `browser_delegate` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetChannelsConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetChannelsConfigOutput>(
            "GetChannelsConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.channels-config-config.read@v1",
            "obs.service.3tched-router.channels-config-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.channels-config-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.channels-config-config.read@v1".to_string(),
            description: "Read the 3tched Router `channels_config` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetCloudOpsConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetCloudOpsConfigOutput>(
            "GetCloudOpsConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.cloud-ops-config.read@v1",
            "obs.service.3tched-router.cloud-ops-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.cloud-ops-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.cloud-ops-config.read@v1".to_string(),
            description: "Read the 3tched Router `cloud_ops` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetComposioConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetComposioConfigOutput>(
            "GetComposioConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.composio-config.read@v1",
            "obs.service.3tched-router.composio-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.composio-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.composio-config.read@v1".to_string(),
            description: "Read the 3tched Router `composio` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetConversationalAiConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetConversationalAiConfigOutput>(
            "GetConversationalAiConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.conversational-ai-config.read@v1",
            "obs.service.3tched-router.conversational-ai-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.conversational-ai-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.conversational-ai-config.read@v1".to_string(),
            description: "Read the 3tched Router `conversational_ai` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetCostConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetCostConfigOutput>(
            "GetCostConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.cost-config.read@v1",
            "obs.service.3tched-router.cost-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.cost-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.cost-config.read@v1".to_string(),
            description: "Read the 3tched Router `cost` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetCronConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetCronConfigOutput>(
            "GetCronConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.cron-config.read@v1",
            "obs.service.3tched-router.cron-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.cron-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.cron-config.read@v1".to_string(),
            description: "Read the 3tched Router `cron` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetDataRetentionConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetDataRetentionConfigOutput>(
            "GetDataRetentionConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.data-retention-config.read@v1",
            "obs.service.3tched-router.data-retention-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.data-retention-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.data-retention-config.read@v1".to_string(),
            description: "Read the 3tched Router `data_retention` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetDelegateConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetDelegateConfigOutput>(
            "GetDelegateConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.delegate-config.read@v1",
            "obs.service.3tched-router.delegate-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.delegate-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.delegate-config.read@v1".to_string(),
            description: "Read the 3tched Router `delegate` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetEmbeddingRoutesConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetEmbeddingRoutesConfigOutput>(
            "GetEmbeddingRoutesConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.embedding-routes-config.read@v1",
            "obs.service.3tched-router.embedding-routes-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.embedding-routes-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.embedding-routes-config.read@v1".to_string(),
            description: "Read the 3tched Router `embedding_routes` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetExtraHeadersConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetExtraHeadersConfigOutput>(
            "GetExtraHeadersConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.extra-headers-config.read@v1",
            "obs.service.3tched-router.extra-headers-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.extra-headers-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.extra-headers-config.read@v1".to_string(),
            description: "Read the 3tched Router `extra_headers` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetGatewayConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetGatewayConfigOutput>(
            "GetGatewayConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.gateway-config.read@v1",
            "obs.service.3tched-router.gateway-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.gateway-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.gateway-config.read@v1".to_string(),
            description: "Read the 3tched Router `gateway` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetGoogleWorkspaceConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetGoogleWorkspaceConfigOutput>(
            "GetGoogleWorkspaceConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.google-workspace-config.read@v1",
            "obs.service.3tched-router.google-workspace-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.google-workspace-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.google-workspace-config.read@v1".to_string(),
            description: "Read the 3tched Router `google_workspace` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetHardwareConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetHardwareConfigOutput>(
            "GetHardwareConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.hardware-config.read@v1",
            "obs.service.3tched-router.hardware-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.hardware-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.hardware-config.read@v1".to_string(),
            description: "Read the 3tched Router `hardware` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetHeartbeatConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetHeartbeatConfigOutput>(
            "GetHeartbeatConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.heartbeat-config.read@v1",
            "obs.service.3tched-router.heartbeat-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.heartbeat-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.heartbeat-config.read@v1".to_string(),
            description: "Read the 3tched Router `heartbeat` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetHooksConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetHooksConfigOutput>(
            "GetHooksConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.hooks-config.read@v1",
            "obs.service.3tched-router.hooks-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.hooks-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.hooks-config.read@v1".to_string(),
            description: "Read the 3tched Router `hooks` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetHttpRequestConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetHttpRequestConfigOutput>(
            "GetHttpRequestConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.http-request-config.read@v1",
            "obs.service.3tched-router.http-request-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.http-request-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.http-request-config.read@v1".to_string(),
            description: "Read the 3tched Router `http_request` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetIdentityConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetIdentityConfigOutput>(
            "GetIdentityConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.identity-config.read@v1",
            "obs.service.3tched-router.identity-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.identity-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.identity-config.read@v1".to_string(),
            description: "Read the 3tched Router `identity` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetJiraConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetJiraConfigOutput>(
            "GetJiraConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.jira-config.read@v1",
            "obs.service.3tched-router.jira-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.jira-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.jira-config.read@v1".to_string(),
            description: "Read the 3tched Router `jira` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetKnowledgeConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetKnowledgeConfigOutput>(
            "GetKnowledgeConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.knowledge-config.read@v1",
            "obs.service.3tched-router.knowledge-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.knowledge-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.knowledge-config.read@v1".to_string(),
            description: "Read the 3tched Router `knowledge` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetLinkedinConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetLinkedinConfigOutput>(
            "GetLinkedinConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.linkedin-config.read@v1",
            "obs.service.3tched-router.linkedin-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.linkedin-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.linkedin-config.read@v1".to_string(),
            description: "Read the 3tched Router `linkedin` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetMcpConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetMcpConfigOutput>(
            "GetMcpConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.mcp-config.read@v1",
            "obs.service.3tched-router.mcp-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.mcp-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.mcp-config.read@v1".to_string(),
            description: "Read the 3tched Router `mcp` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetMemoryConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetMemoryConfigOutput>(
            "GetMemoryConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.memory-config.read@v1",
            "obs.service.3tched-router.memory-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.memory-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.memory-config.read@v1".to_string(),
            description: "Read the 3tched Router `memory` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetMicrosoft365Config".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetMicrosoft365ConfigOutput>(
            "GetMicrosoft365Config",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.microsoft365-config.read@v1",
            "obs.service.3tched-router.microsoft365-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.microsoft365-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.microsoft365-config.read@v1".to_string(),
            description: "Read the 3tched Router `microsoft365` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetModelProvidersConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetModelProvidersConfigOutput>(
            "GetModelProvidersConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.model-providers-config.read@v1",
            "obs.service.3tched-router.model-providers-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.model-providers-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.model-providers-config.read@v1".to_string(),
            description: "Read the 3tched Router `model_providers` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetModelRoutesConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetModelRoutesConfigOutput>(
            "GetModelRoutesConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.model-routes-config.read@v1",
            "obs.service.3tched-router.model-routes-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.model-routes-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.model-routes-config.read@v1".to_string(),
            description: "Read the 3tched Router `model_routes` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetMultimodalConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetMultimodalConfigOutput>(
            "GetMultimodalConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.multimodal-config.read@v1",
            "obs.service.3tched-router.multimodal-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.multimodal-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.multimodal-config.read@v1".to_string(),
            description: "Read the 3tched Router `multimodal` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetNodeTransportConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetNodeTransportConfigOutput>(
            "GetNodeTransportConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.node-transport-config.read@v1",
            "obs.service.3tched-router.node-transport-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.node-transport-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.node-transport-config.read@v1".to_string(),
            description: "Read the 3tched Router `node_transport` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetNodesConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetNodesConfigOutput>(
            "GetNodesConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.nodes-config.read@v1",
            "obs.service.3tched-router.nodes-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.nodes-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.nodes-config.read@v1".to_string(),
            description: "Read the 3tched Router `nodes` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetNotionConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetNotionConfigOutput>(
            "GetNotionConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.notion-config.read@v1",
            "obs.service.3tched-router.notion-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.notion-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.notion-config.read@v1".to_string(),
            description: "Read the 3tched Router `notion` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetObservabilityConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetObservabilityConfigOutput>(
            "GetObservabilityConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.observability-config.read@v1",
            "obs.service.3tched-router.observability-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.observability-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.observability-config.read@v1".to_string(),
            description: "Read the 3tched Router `observability` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetPeripheralsConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetPeripheralsConfigOutput>(
            "GetPeripheralsConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.peripherals-config.read@v1",
            "obs.service.3tched-router.peripherals-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.peripherals-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.peripherals-config.read@v1".to_string(),
            description: "Read the 3tched Router `peripherals` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetPluginsConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetPluginsConfigOutput>(
            "GetPluginsConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.plugins-config.read@v1",
            "obs.service.3tched-router.plugins-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.plugins-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.plugins-config.read@v1".to_string(),
            description: "Read the 3tched Router `plugins` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetProjectIntelConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetProjectIntelConfigOutput>(
            "GetProjectIntelConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.project-intel-config.read@v1",
            "obs.service.3tched-router.project-intel-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.project-intel-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.project-intel-config.read@v1".to_string(),
            description: "Read the 3tched Router `project_intel` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetProxyConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetProxyConfigOutput>(
            "GetProxyConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.proxy-config.read@v1",
            "obs.service.3tched-router.proxy-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.proxy-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.proxy-config.read@v1".to_string(),
            description: "Read the 3tched Router `proxy` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetQueryClassificationConfig".to_string(),
        method_decl_from_schemars_with_output::<
            ConfigMethodInput,
            GetQueryClassificationConfigOutput,
        >(
            "GetQueryClassificationConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.query-classification-config.read@v1",
            "obs.service.3tched-router.query-classification-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.query-classification-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.query-classification-config.read@v1".to_string(),
            description: "Read the 3tched Router `query_classification` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetReliabilityConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetReliabilityConfigOutput>(
            "GetReliabilityConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.reliability-config.read@v1",
            "obs.service.3tched-router.reliability-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.reliability-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.reliability-config.read@v1".to_string(),
            description: "Read the 3tched Router `reliability` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetRuntimeConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetRuntimeConfigOutput>(
            "GetRuntimeConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.runtime-config.read@v1",
            "obs.service.3tched-router.runtime-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.runtime-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.runtime-config.read@v1".to_string(),
            description: "Read the 3tched Router `runtime` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetSchedulerConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetSchedulerConfigOutput>(
            "GetSchedulerConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.scheduler-config.read@v1",
            "obs.service.3tched-router.scheduler-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.scheduler-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.scheduler-config.read@v1".to_string(),
            description: "Read the 3tched Router `scheduler` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetSecretsConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetSecretsConfigOutput>(
            "GetSecretsConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.secrets-config.read@v1",
            "obs.service.3tched-router.secrets-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.secrets-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.secrets-config.read@v1".to_string(),
            description: "Read the 3tched Router `secrets` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetSecurityConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetSecurityConfigOutput>(
            "GetSecurityConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.security-config.read@v1",
            "obs.service.3tched-router.security-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.security-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.security-config.read@v1".to_string(),
            description: "Read the 3tched Router `security` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetSecurityOpsConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetSecurityOpsConfigOutput>(
            "GetSecurityOpsConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.security-ops-config.read@v1",
            "obs.service.3tched-router.security-ops-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.security-ops-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.security-ops-config.read@v1".to_string(),
            description: "Read the 3tched Router `security_ops` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetSkillsConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetSkillsConfigOutput>(
            "GetSkillsConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.skills-config.read@v1",
            "obs.service.3tched-router.skills-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.skills-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.skills-config.read@v1".to_string(),
            description: "Read the 3tched Router `skills` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetStorageConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetStorageConfigOutput>(
            "GetStorageConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.storage-config.read@v1",
            "obs.service.3tched-router.storage-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.storage-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.storage-config.read@v1".to_string(),
            description: "Read the 3tched Router `storage` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetSwarmsConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetSwarmsConfigOutput>(
            "GetSwarmsConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.swarms-config.read@v1",
            "obs.service.3tched-router.swarms-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.swarms-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.swarms-config.read@v1".to_string(),
            description: "Read the 3tched Router `swarms` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetTextBrowserConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetTextBrowserConfigOutput>(
            "GetTextBrowserConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.text-browser-config.read@v1",
            "obs.service.3tched-router.text-browser-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.text-browser-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.text-browser-config.read@v1".to_string(),
            description: "Read the 3tched Router `text_browser` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetTranscriptionConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetTranscriptionConfigOutput>(
            "GetTranscriptionConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.transcription-config.read@v1",
            "obs.service.3tched-router.transcription-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.transcription-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.transcription-config.read@v1".to_string(),
            description: "Read the 3tched Router `transcription` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetTtsConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetTtsConfigOutput>(
            "GetTtsConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.tts-config.read@v1",
            "obs.service.3tched-router.tts-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.tts-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.tts-config.read@v1".to_string(),
            description: "Read the 3tched Router `tts` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetTunnelConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetTunnelConfigOutput>(
            "GetTunnelConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.tunnel-config.read@v1",
            "obs.service.3tched-router.tunnel-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.tunnel-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.tunnel-config.read@v1".to_string(),
            description: "Read the 3tched Router `tunnel` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetWebFetchConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetWebFetchConfigOutput>(
            "GetWebFetchConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.web-fetch-config.read@v1",
            "obs.service.3tched-router.web-fetch-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.web-fetch-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.web-fetch-config.read@v1".to_string(),
            description: "Read the 3tched Router `web_fetch` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetWebSearchConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetWebSearchConfigOutput>(
            "GetWebSearchConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.web-search-config.read@v1",
            "obs.service.3tched-router.web-search-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.web-search-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.web-search-config.read@v1".to_string(),
            description: "Read the 3tched Router `web_search` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetWorkspaceConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetWorkspaceConfigOutput>(
            "GetWorkspaceConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.workspace-config.read@v1",
            "obs.service.3tched-router.workspace-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.workspace-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.workspace-config.read@v1".to_string(),
            description: "Read the 3tched Router `workspace` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetModelAssignmentsConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetModelAssignmentsConfigOutput>(
            "GetModelAssignmentsConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.model-assignments-config.read@v1",
            "obs.service.3tched-router.model-assignments-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.model-assignments-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.model-assignments-config.read@v1".to_string(),
            description: "Read the 3tched Router `model_assignments` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetMemoryNamespacesConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetMemoryNamespacesConfigOutput>(
            "GetMemoryNamespacesConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.memory-namespaces-config.read@v1",
            "obs.service.3tched-router.memory-namespaces-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.memory-namespaces-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.memory-namespaces-config.read@v1".to_string(),
            description: "Read the 3tched Router `memory_namespaces` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetRegistrationServiceConfig".to_string(),
        method_decl_from_schemars_with_output::<
            ConfigMethodInput,
            GetRegistrationServiceConfigOutput,
        >(
            "GetRegistrationServiceConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.registration-service-config.read@v1",
            "obs.service.3tched-router.registration-service-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.registration-service-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.registration-service-config.read@v1".to_string(),
            description: "Read the 3tched Router `registration_service` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetUserContainerConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetUserContainerConfigOutput>(
            "GetUserContainerConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.user-container-config.read@v1",
            "obs.service.3tched-router.user-container-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.user-container-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.user-container-config.read@v1".to_string(),
            description: "Read the 3tched Router `user_container` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetIdentityChainConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetIdentityChainConfigOutput>(
            "GetIdentityChainConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.identity-chain-config.read@v1",
            "obs.service.3tched-router.identity-chain-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.identity-chain-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.identity-chain-config.read@v1".to_string(),
            description: "Read the 3tched Router `identity_chain` configuration.".to_string(),
        },
    );
    schema.methods.insert(
        "GetPrivacyPolicyConfig".to_string(),
        method_decl_from_schemars_with_output::<ConfigMethodInput, GetPrivacyPolicyConfigOutput>(
            "GetPrivacyPolicyConfig",
            SideEffect::Read,
            true,
            "cap.software.3tched-router.privacy-policy-config.read@v1",
            "obs.service.3tched-router.privacy-policy-config.get@v1",
        ),
    );
    schema.capabilities.insert(
        "cap.software.3tched-router.privacy-policy-config.read@v1".to_string(),
        CapabilityDecl {
            id: "cap.software.3tched-router.privacy-policy-config.read@v1".to_string(),
            description: "Read the 3tched Router `privacy_policy` configuration.".to_string(),
        },
    );
}

// ── Dispatch ────────────────────────────────────────────────────────────────

/// Dispatch a config-surface method. Returns `None` when `method` is not
/// owned by this surface so the caller can fall through to other dispatchers.
pub fn dispatch_config_method(
    method: &str,
    json_args: &str,
    state: &TchedRouterState,
) -> Option<std::result::Result<DispatchOutcome, TchedRouterError>> {
    match method {
        "GetConfig" => Some(get_full_config()),
        "PatchConfig" => Some(patch_config(json_args)),
        other => SECTIONS
            .iter()
            .find(|(name, _, _)| *name == other)
            .map(|(_, key, source)| read_section(key, *source, state)),
    }
}

/// Path of the live 3tched Router config file.
///
/// Minimal mirror of upstream resolution for now: explicit
/// `TCHED_ROUTER_CONFIG_PATH` / `ZEROCLAW_CONFIG_PATH` override, else the
/// default `~/.zeroclaw/config.toml`. Upstream's full resolution (workspace
/// marker, env dirs) should replace this once exposed by the `zeroclaw` crate.
fn config_path() -> std::path::PathBuf {
    if let Ok(p) = std::env::var("TCHED_ROUTER_CONFIG_PATH") {
        return p.into();
    }
    if let Ok(p) = std::env::var("ZEROCLAW_CONFIG_PATH") {
        return p.into();
    }
    dirs::home_dir()
        .unwrap_or_else(|| std::path::PathBuf::from("/root"))
        .join(".zeroclaw")
        .join("config.toml")
}

/// Read the config file and parse it through the REAL upstream type — an
/// invalid file is an error here, never a silent partial read.
fn load_upstream_value() -> std::result::Result<JsonValue, TchedRouterError> {
    let path = config_path();
    let text = std::fs::read_to_string(&path).map_err(|e| TchedRouterError::ExecutionDenied {
        reason: format!("read {}: {e}", path.display()),
    })?;
    let config: zeroclaw::Config =
        toml::from_str(&text).map_err(|e| TchedRouterError::ExecutionDenied {
            reason: format!("parse {}: {e}", path.display()),
        })?;
    serde_json::to_value(&config).map_err(|e| TchedRouterError::ExecutionDenied {
        reason: format!("serialize config: {e}"),
    })
}

fn read_section(
    key: &str,
    source: SectionSource,
    state: &TchedRouterState,
) -> std::result::Result<DispatchOutcome, TchedRouterError> {
    let root = match source {
        SectionSource::Upstream => load_upstream_value()?,
        SectionSource::Local => {
            serde_json::to_value(state).map_err(|e| TchedRouterError::ExecutionDenied {
                reason: format!("serialize state: {e}"),
            })?
        }
    };
    let value = root
        .get(key)
        .cloned()
        .ok_or_else(|| TchedRouterError::ExecutionDenied {
            reason: format!("config section missing: {key}"),
        })?;
    Ok(DispatchOutcome::plain(
        serde_json::json!({ "config": value }),
    ))
}

fn get_full_config() -> std::result::Result<DispatchOutcome, TchedRouterError> {
    let mut root = load_upstream_value()?;
    mask_secrets(&mut root);
    Ok(DispatchOutcome::plain(
        serde_json::json!({ "config": root }),
    ))
}

fn patch_config(json_args: &str) -> std::result::Result<DispatchOutcome, TchedRouterError> {
    #[derive(Deserialize)]
    struct Args {
        section: String,
        value: JsonValue,
    }
    let args: Args =
        serde_json::from_str(json_args).map_err(|e| TchedRouterError::ExecutionDenied {
            reason: format!("PatchConfig args: {e}"),
        })?;
    if !SECTIONS
        .iter()
        .any(|(_, key, source)| *key == args.section && *source == SectionSource::Upstream)
    {
        return Err(TchedRouterError::ExecutionDenied {
            reason: format!(
                "PatchConfig: unknown or non-upstream section `{}` \
                 (local sections are mutated via their own Set* methods)",
                args.section
            ),
        });
    }
    if contains_masked_placeholder(&args.value) {
        return Err(TchedRouterError::ExecutionDenied {
            reason: "PatchConfig: value contains \"***MASKED***\" — masked \
                     placeholders cannot be written"
                .to_string(),
        });
    }
    let path = config_path();
    let text = std::fs::read_to_string(&path).map_err(|e| TchedRouterError::ExecutionDenied {
        reason: format!("read {}: {e}", path.display()),
    })?;
    let mut doc: toml::Value =
        toml::from_str(&text).map_err(|e| TchedRouterError::ExecutionDenied {
            reason: format!("parse {}: {e}", path.display()),
        })?;
    let table = doc
        .as_table_mut()
        .ok_or_else(|| TchedRouterError::ExecutionDenied {
            reason: "config root is not a table".to_string(),
        })?;
    let new_toml: toml::Value = serde_json::from_value(args.value.clone()).map_err(|e| {
        TchedRouterError::ExecutionDenied {
            reason: format!("section value is not TOML-representable: {e}"),
        }
    })?;
    table.insert(args.section.clone(), new_toml);
    let serialized = toml::to_string(&doc).map_err(|e| TchedRouterError::ExecutionDenied {
        reason: format!("serialize config: {e}"),
    })?;
    // Validate against the REAL upstream type before writing.
    let _: zeroclaw::Config =
        toml::from_str(&serialized).map_err(|e| TchedRouterError::ExecutionDenied {
            reason: format!("patched config fails upstream validation: {e}"),
        })?;
    write_config_atomically(&path, &serialized)?;
    Ok(DispatchOutcome::plain(serde_json::json!({
        "section": args.section,
        "value": args.value,
    })))
}

/// Durably replace the live config without exposing a truncated intermediate file.
fn write_config_atomically(
    path: &std::path::Path,
    serialized: &str,
) -> std::result::Result<(), TchedRouterError> {
    use std::io::Write;
    use std::os::fd::AsRawFd;
    use std::os::unix::fs::MetadataExt;

    // Follow an operator-supplied symlink exactly as the previous in-place
    // write did, while still staging on the target's filesystem.
    let resolved =
        std::fs::canonicalize(path).map_err(|e| TchedRouterError::ExecutionDenied {
            reason: format!("resolve config path {}: {e}", path.display()),
        })?;
    let metadata =
        std::fs::metadata(&resolved).map_err(|e| TchedRouterError::ExecutionDenied {
            reason: format!("read config metadata {}: {e}", resolved.display()),
        })?;
    let parent = resolved
        .parent()
        .ok_or_else(|| TchedRouterError::ExecutionDenied {
            reason: format!("config path has no parent: {}", resolved.display()),
        })?;
    let mut staged =
        tempfile::NamedTempFile::new_in(parent).map_err(|e| TchedRouterError::ExecutionDenied {
            reason: format!("stage config beside {}: {e}", resolved.display()),
        })?;
    staged
        .write_all(serialized.as_bytes())
        .map_err(|e| TchedRouterError::ExecutionDenied {
            reason: format!("write staged config for {}: {e}", resolved.display()),
        })?;
    // Writing can clear set-id mode bits and security attributes. Restore all
    // inherited metadata only after the staged contents are final.
    nix::unistd::fchown(
        staged.as_file().as_raw_fd(),
        Some(nix::unistd::Uid::from_raw(metadata.uid())),
        Some(nix::unistd::Gid::from_raw(metadata.gid())),
    )
    .map_err(|e| TchedRouterError::ExecutionDenied {
        reason: format!("preserve config ownership for {}: {e}", resolved.display()),
    })?;
    staged
        .as_file()
        .set_permissions(metadata.permissions())
        .map_err(|e| TchedRouterError::ExecutionDenied {
            reason: format!("preserve config permissions for {}: {e}", resolved.display()),
        })?;
    for name in xattr::list(&resolved).map_err(|e| TchedRouterError::ExecutionDenied {
        reason: format!("list config attributes for {}: {e}", resolved.display()),
    })? {
        let value = xattr::get(&resolved, &name)
            .map_err(|e| TchedRouterError::ExecutionDenied {
                reason: format!(
                    "read config attribute {:?} for {}: {e}",
                    name,
                    resolved.display()
                ),
            })?
            .ok_or_else(|| TchedRouterError::ExecutionDenied {
                reason: format!(
                    "config attribute {:?} disappeared from {}",
                    name,
                    resolved.display()
                ),
            })?;
        xattr::set(staged.path(), &name, &value).map_err(|e| {
            TchedRouterError::ExecutionDenied {
                reason: format!(
                    "preserve config attribute {:?} for {}: {e}",
                    name,
                    resolved.display()
                ),
            }
        })?;
    }
    staged
        .as_file_mut()
        .sync_all()
        .map_err(|e| TchedRouterError::ExecutionDenied {
            reason: format!("sync staged config for {}: {e}", resolved.display()),
        })?;
    staged
        .persist(&resolved)
        .map_err(|e| TchedRouterError::ExecutionDenied {
            reason: format!(
                "replace {} with staged config: {}",
                resolved.display(),
                e.error
            ),
        })?;
    std::fs::File::open(parent)
        .and_then(|directory| directory.sync_all())
        .map_err(|e| TchedRouterError::ExecutionDenied {
            reason: format!("sync config directory {}: {e}", parent.display()),
        })
}

/// Recursively mask secret-bearing keys in a config value.
fn mask_secrets(value: &mut JsonValue) {
    const SECRET_KEYS: &[&str] = &[
        "api_key",
        "apikey",
        "token",
        "secret",
        "password",
        "private_key",
    ];
    match value {
        JsonValue::Object(map) => {
            for (k, v) in map.iter_mut() {
                let lk = k.to_ascii_lowercase();
                if SECRET_KEYS.iter().any(|s| lk.contains(s)) && v.is_string() {
                    *v = JsonValue::String("***MASKED***".to_string());
                } else {
                    mask_secrets(v);
                }
            }
        }
        JsonValue::Array(items) => items.iter_mut().for_each(mask_secrets),
        _ => {}
    }
}

fn contains_masked_placeholder(value: &JsonValue) -> bool {
    match value {
        JsonValue::String(s) => s == "***MASKED***",
        JsonValue::Array(items) => items.iter().any(contains_masked_placeholder),
        JsonValue::Object(map) => map.values().any(contains_masked_placeholder),
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::{symlink, MetadataExt, PermissionsExt};

    #[test]
    fn patch_config_preserves_live_file_when_atomic_staging_fails() {
        let dir = tempfile::tempdir().expect("temp config directory");
        let path = dir.path().join("config.toml");
        symlink("/proc/version", &path).expect("link to deterministic read-only target");
        let original = std::fs::read_to_string(&path).expect("read original target");

        assert!(
            write_config_atomically(&path, "destroyed").is_err_and(
                |error| error.to_string().contains("stage config beside /proc/version")
            ),
            "patch must fail specifically while staging"
        );
        assert!(
            std::fs::symlink_metadata(&path)
                .expect("link metadata")
                .file_type()
                .is_symlink(),
            "failed patch must preserve the configured symlink"
        );
        assert_eq!(
            std::fs::read_to_string(&path).expect("read target after failed patch"),
            original,
            "failed patch must preserve live config"
        );
    }

    #[test]
    fn atomic_config_write_follows_symlink_and_preserves_metadata() {
        let dir = tempfile::tempdir().expect("temp config directory");
        let target = dir.path().join("config-target.toml");
        let path = dir.path().join("config.toml");
        std::fs::write(&target, "old").expect("write original config");
        std::fs::set_permissions(&target, std::fs::Permissions::from_mode(0o4640))
            .expect("set original permissions");
        xattr::set(&target, "user.opdbus-test", b"preserve").expect("set original xattr");
        let original_metadata = std::fs::metadata(&target).expect("original metadata");
        symlink(&target, &path).expect("create config symlink");

        write_config_atomically(&path, "new").expect("replace config atomically");

        assert!(
            std::fs::symlink_metadata(&path)
                .expect("link metadata")
                .file_type()
                .is_symlink(),
            "atomic replacement must not replace the configured symlink"
        );
        assert_eq!(
            std::fs::read_to_string(&target).expect("read replaced target"),
            "new"
        );
        let replaced_metadata = std::fs::metadata(&target).expect("replaced metadata");
        assert_eq!(replaced_metadata.uid(), original_metadata.uid());
        assert_eq!(replaced_metadata.gid(), original_metadata.gid());
        assert_eq!(replaced_metadata.mode() & 0o7777, 0o4640);
        assert_eq!(
            xattr::get(&target, "user.opdbus-test").expect("read replaced xattr"),
            Some(b"preserve".to_vec())
        );
    }
}
