#!/bin/sh
exec 2>&1
[ -r /etc/op-dbus/environment ] && . /etc/op-dbus/environment
export DBUS_SESSION_BUS_ADDRESS
: "${DBUS_SESSION_BUS_ADDRESS:?DBUS_SESSION_BUS_ADDRESS must be set in /etc/op-dbus/environment}"
export PRIVACY_DATAPATH_TYPE="${PRIVACY_DATAPATH_TYPE:-netdev}"
export PRIVACY_FAIL_MODE="${PRIVACY_FAIL_MODE:-standalone}"
export PRIVACY_UPLINK_PORT="${PRIVACY_UPLINK_PORT:-eth0}"
export NEXTDNS_PROFILE_ID="${NEXTDNS_PROFILE_ID:-689ec7}"
export SCHEMA_UUID="${SCHEMA_UUID:-761b8b60-cde0-51f5-a3d6-cc07308b85b7}"
export SCHEMA_SUBID="${SCHEMA_SUBID:-sch.net.wireguard@v1}"
export SCHEMA_CONTROL_SOURCE="${SCHEMA_CONTROL_SOURCE:-NIST_SP_800_53_R5}"
exec /usr/local/bin/opdbus
