#!/bin/bash
set -e

echo "🌐 Setting up Antigravity IDE for REMOTE MCP Servers"
echo "📍 Antigravity is on a different server than your MCP servers"
echo ""

# Check if Antigravity config directory exists (on the machine where Antigravity runs)
ANTIGRAVITY_CONFIG_DIR="$HOME/.config/antigravity"
echo "📁 Antigravity config directory: $ANTIGRAVITY_CONFIG_DIR"

# Create directory if it doesn't exist
mkdir -p "$ANTIGRAVITY_CONFIG_DIR"

# Copy the remote agent configuration
CONFIG_FILE="$ANTIGRAVITY_CONFIG_DIR/mcp.json"
cp antigravity-remote-config.json "$CONFIG_FILE"

echo "✅ Remote configuration copied to: $CONFIG_FILE"

# Set proper permissions
chmod 644 "$CONFIG_FILE"

echo ""
echo "🔧 Your MCP servers need to be exposed via HTTP endpoints that Antigravity can reach:"
echo ""
echo "1. 🌐 Main MCP Aggregator: https://mcp.ghostbridge.tech"
echo "2. 🤖 Agents Server:       https://agents.ghostbridge.tech"
echo "3. 🔧 SystemD Service:     https://mcp-servers.ghostbridge.tech:8091"
echo "4. 🔐 Login Service:       https://mcp-servers.ghostbridge.tech:8092"
echo "5. ⚙️  Core Service:        https://mcp-servers.ghostbridge.tech:8093"
echo ""

echo "📋 Required server-side setup (on your MCP server):"
echo ""

echo "Step 1: Install HTTP MCP proxy servers"
echo "----------------------------------------"
echo "# Build the HTTP MCP proxy"
echo "cd /home/jeremy/git/op-dbus-p1/crates/op-mcp"
echo "cargo build --release --bin mcp-http-proxy"
echo ""

echo "Step 2: Configure systemd services for HTTP exposure"
echo "---------------------------------------------------"
echo "# Create systemd service files for HTTP MCP servers"
echo "sudo cp deploy/systemd/op-mcp-http@.service /etc/systemd/system/"
echo "sudo systemctl daemon-reload"
echo ""

echo "Step 3: Start HTTP MCP services"
echo "--------------------------------"
echo "sudo systemctl enable op-mcp-http@8091  # SystemD service"
echo "sudo systemctl enable op-mcp-http@8092  # Login service"
echo "sudo systemctl enable op-mcp-http@8093  # Core service"
echo "sudo systemctl start op-mcp-http@8091"
echo "sudo systemctl start op-mcp-http@8092"
echo "sudo systemctl start op-mcp-http@8093"
echo ""

echo "Step 4: Configure Cloudflare for subdomain routing"
echo "-------------------------------------------------"
echo "# Add DNS records in Cloudflare:"
echo "# - mcp.ghostbridge.tech     -> your-server-ip (port 443 -> 8081)"
echo "# - agents.ghostbridge.tech  -> your-server-ip (port 443 -> 8082)"
echo "# - mcp-servers.ghostbridge.tech -> your-server-ip (ports 443 -> 8091-8093)"
echo ""

echo "Step 5: Update Caddyfile for HTTP MCP routing"
echo "---------------------------------------------"
echo "# Add to /etc/caddy/Caddyfile:"
echo "mcp.ghostbridge.tech {"
echo "    reverse_proxy localhost:8081"
echo "}"
echo ""
echo "agents.ghostbridge.tech {"
echo "    reverse_proxy localhost:8082"
echo "}"
echo ""
echo "mcp-servers.ghostbridge.tech {"
echo "    reverse_proxy localhost:8091"
echo "    "
echo "    @systemd host mcp-servers.ghostbridge.tech"
echo "    handle @systemd {"
echo "        uri strip_prefix /systemd"
echo "        reverse_proxy localhost:8091"
echo "    }"
echo "    "
echo "    @login host mcp-servers.ghostbridge.tech"
echo "    handle @login {"
echo "        uri strip_prefix /login"
echo "        reverse_proxy localhost:8092"
echo "    }"
echo "    "
echo "    @core host mcp-servers.ghostbridge.tech"
echo "    handle @core {"
echo "        uri strip_prefix /core"
echo "        reverse_proxy localhost:8093"
echo "    }"
echo "}"
echo ""

echo "🎯 Alternative: SSH Tunneling (if you don't want public exposure)"
echo "-----------------------------------------------------------------"
echo "# On the machine running Antigravity:"
echo "ssh -L 8081:localhost:8081 jeremy@your-mcp-server"
echo "ssh -L 8082:localhost:8082 jeremy@your-mcp-server"
echo "ssh -L 8091:localhost:8091 jeremy@your-mcp-server"
echo "ssh -L 8092:localhost:8092 jeremy@your-mcp-server"
echo "ssh -L 8093:localhost:8093 jeremy@your-mcp-server"
echo ""
echo "# Then use localhost URLs in Antigravity config:"
echo "# http://localhost:8081, http://localhost:8082, etc."
echo ""

echo "🔍 Testing connectivity:"
echo "----------------------"
echo "# Test from Antigravity machine:"
echo "curl https://mcp.ghostbridge.tech/health"
echo "curl https://agents.ghostbridge.tech/health"
echo "curl https://mcp-servers.ghostbridge.tech:8091/health"
echo ""

echo "📚 Documentation: See ANTIGRAVITY-REMOTE-README.md"
echo ""
echo "⚠️  SECURITY NOTE: Ensure proper authentication and HTTPS!"
echo ""
echo "🎉 Antigravity will now connect to your remote MCP servers!"
