//! Shared helpers for converting between JSON values returned by the Assistant
//! HTTP API and the proto types generated by tonic.

use prost_types::value::Kind;
use prost_types::{ListValue, Struct, Timestamp, Value as PValue};
use serde_json::{Map, Value};

pub fn str_field(v: &Value, key: &str) -> String {
    v.get(key)
        .and_then(|s| s.as_str())
        .unwrap_or_default()
        .to_string()
}

pub fn u32_field(v: &Value, key: &str) -> u32 {
    v.get(key).and_then(|n| n.as_u64()).unwrap_or(0) as u32
}

pub fn u64_field(v: &Value, key: &str) -> u64 {
    v.get(key).and_then(|n| n.as_u64()).unwrap_or(0)
}

pub fn bool_field(v: &Value, key: &str) -> bool {
    v.get(key).and_then(|n| n.as_bool()).unwrap_or(false)
}

pub fn opt_str(v: &Value, key: &str) -> Option<String> {
    v.get(key).and_then(|s| s.as_str()).map(String::from)
}

pub fn string_list(v: &Value, key: &str) -> Vec<String> {
    v.get(key)
        .and_then(|s| s.as_array())
        .map(|a| {
            a.iter()
                .filter_map(|s| s.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default()
}

pub fn ts_field(v: &Value, key: &str) -> Option<Timestamp> {
    let raw = v.get(key)?;
    if let Some(s) = raw.as_str() {
        if let Ok(dt) = chrono::DateTime::parse_from_rfc3339(s) {
            return Some(Timestamp {
                seconds: dt.timestamp(),
                nanos: dt.timestamp_subsec_nanos() as i32,
            });
        }
    }
    if let Some(secs) = raw.as_i64() {
        return Some(Timestamp {
            seconds: secs,
            nanos: 0,
        });
    }
    None
}

pub fn struct_to_json(s: Struct) -> Value {
    let mut map = Map::with_capacity(s.fields.len());
    for (k, v) in s.fields {
        map.insert(k, pvalue_to_json(v));
    }
    Value::Object(map)
}

pub fn pvalue_to_json(p: PValue) -> Value {
    match p.kind {
        None | Some(Kind::NullValue(_)) => Value::Null,
        Some(Kind::BoolValue(b)) => Value::Bool(b),
        Some(Kind::NumberValue(n)) => serde_json::Number::from_f64(n)
            .map(Value::Number)
            .unwrap_or(Value::Null),
        Some(Kind::StringValue(s)) => Value::String(s),
        Some(Kind::StructValue(s)) => struct_to_json(s),
        Some(Kind::ListValue(ListValue { values })) => {
            Value::Array(values.into_iter().map(pvalue_to_json).collect())
        }
    }
}

pub fn json_to_struct(v: Value) -> Struct {
    match v {
        Value::Object(map) => Struct {
            fields: map.into_iter().map(|(k, v)| (k, json_to_pvalue(v))).collect(),
        },
        _ => Struct::default(),
    }
}

pub fn json_to_pvalue(v: Value) -> PValue {
    let kind = match v {
        Value::Null => Kind::NullValue(0),
        Value::Bool(b) => Kind::BoolValue(b),
        Value::Number(n) => Kind::NumberValue(n.as_f64().unwrap_or(0.0)),
        Value::String(s) => Kind::StringValue(s),
        Value::Array(arr) => Kind::ListValue(ListValue {
            values: arr.into_iter().map(json_to_pvalue).collect(),
        }),
        Value::Object(map) => Kind::StructValue(Struct {
            fields: map.into_iter().map(|(k, v)| (k, json_to_pvalue(v))).collect(),
        }),
    };
    PValue { kind: Some(kind) }
}

pub fn opt_struct(v: &Value, key: &str) -> Option<Struct> {
    v.get(key).cloned().map(json_to_struct)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn struct_roundtrip() {
        let original = json!({"a": 1.0, "b": "x", "c": [true, null]});
        let s = json_to_struct(original.clone());
        let back = struct_to_json(s);
        assert_eq!(back, original);
    }

    #[test]
    fn ts_parses_rfc3339() {
        let v = json!({"t": "2024-01-02T03:04:05Z"});
        let t = ts_field(&v, "t").unwrap();
        assert!(t.seconds > 0);
    }
}
