[package]
name = "op-reflection-socket"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "op-reflection-socket"
path = "src/main.rs"

[dependencies]
tonic = { workspace = true }
tonic-reflection = { workspace = true }
prost = { workspace = true }
prost-reflect = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }
bytes = { workspace = true }
http-body = "1"
http-body-util = "0.1"
prost-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
op-blob = { path = "../op-blob" }
op-state-store = { path = "../op-state-store" }
op-identity = { path = "../op-identity" }
hex = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
