#!/usr/bin/env bash
# Code Assist Gateway - client setup script
# Routes ALL Gemini/Vertex traffic through cloudcode-pa.googleapis.com
# (VS Code Code Assist masking → Enterprise Plus quota → no per-token charges)
#
# Run once per client machine. Safe to re-run.
#
# Requirements: gcloud or VS Code Cloud Code extension auth
# Optional:     NEXTDNS_API_KEY env var to auto-configure DNS rewrites
set -euo pipefail

HTTP_PORT="${CODE_ASSIST_HTTP_PORT:-8642}"
HTTPS_PORT="${CODE_ASSIST_HTTPS_PORT:-4443}"
BIND="127.0.0.1"
CERT_DIR="${CODE_ASSIST_CERT_DIR:-$HOME/.config/code-assist-gateway}"
NEXTDNS_PROFILE="${NEXTDNS_PROFILE:-689ec7}"
PROXY_BIN=""

BILLABLE_DOMAINS=(
  "generativelanguage.googleapis.com"
  "aiplatform.googleapis.com"
)

log()  { printf '\033[1;34m>>>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m  ✓\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m  !\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# ── 1. Binary ─────────────────────────────────────────────────────────────────

find_or_build_binary() {
  log "Locating op-mcp-proxy..."
  local candidates=(
    "/usr/local/bin/op-mcp-proxy"
    "$HOME/.local/bin/op-mcp-proxy"
  )
  # repo-relative candidates
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  candidates+=(
    "$script_dir/../target/release/op-mcp-proxy"
    "$script_dir/../target/debug/op-mcp-proxy"
  )

  for p in "${candidates[@]}"; do
    if [ -x "$p" ]; then
      PROXY_BIN="$p"
      ok "Found binary: $PROXY_BIN"
      return
    fi
  done

  local repo="$script_dir/.."
  if [ -f "$repo/Cargo.toml" ]; then
    log "Building op-mcp-proxy (release)..."
    (cd "$repo" && cargo build --release -p op-mcp-proxy 2>&1 | tail -5) \
      || die "Build failed"
    PROXY_BIN="$repo/target/release/op-mcp-proxy"
    mkdir -p "$HOME/.local/bin"
    cp "$PROXY_BIN" "$HOME/.local/bin/op-mcp-proxy"
    PROXY_BIN="$HOME/.local/bin/op-mcp-proxy"
    ok "Built and installed: $PROXY_BIN"
    return
  fi

  die "Cannot find or build op-mcp-proxy. Build from repo or copy binary to /usr/local/bin."
}

# ── 2. Auth check ──────────────────────────────────────────────────────────────

check_auth() {
  log "Checking credentials..."

  local ext="$HOME/.cache/google-vscode-extension/auth/application_default_credentials.json"
  if [ -f "$ext" ]; then
    local has_rt
    has_rt=$(python3 -c "import json; d=json.load(open('$ext')); print('yes' if d.get('refresh_token') else 'no')" 2>/dev/null || echo "no")
    if [ "$has_rt" = "yes" ]; then
      ok "VS Code Cloud Code extension credentials (preferred)"
      return
    fi
  fi

  if command -v gcloud >/dev/null 2>&1 && gcloud auth print-access-token >/dev/null 2>&1; then
    ok "gcloud CLI credentials"
    return
  fi

  warn "No credentials found. The gateway will start but requests will fail until you authenticate."
  echo "    Option 1 (best): Sign into VS Code Cloud Code extension"
  echo "    Option 2: gcloud auth login && gcloud auth application-default login"
}

# ── 3. TLS cert + system trust ────────────────────────────────────────────────

setup_tls() {
  log "Setting up TLS certificate..."
  mkdir -p "$CERT_DIR"

  local cert="$CERT_DIR/cert.pem"

  if [ -f "$cert" ]; then
    ok "Cert already exists: $cert"
  else
    # Generate via the gateway itself (rcgen), or mkcert if available
    if command -v mkcert >/dev/null 2>&1; then
      (cd "$CERT_DIR" && mkcert -cert-file cert.pem -key-file key.pem \
        generativelanguage.googleapis.com \
        aiplatform.googleapis.com \
        localhost 127.0.0.1 2>&1)
      ok "Generated cert via mkcert (auto-trusted)"
    else
      ok "Cert will be generated by gateway on first start (rcgen self-signed)"
      warn "You will need to trust it manually:"
      _print_trust_instructions
    fi
  fi

  # Install trust if cert exists
  if [ -f "$cert" ]; then
    _install_trust "$cert"
  fi
}

_install_trust() {
  local cert="$1"
  if [ "$(uname)" = "Linux" ]; then
    local ca_dir="/usr/local/share/ca-certificates"
    local dest="$ca_dir/code-assist-gateway.crt"
    if [ ! -f "$dest" ] || ! diff -q "$cert" "$dest" >/dev/null 2>&1; then
      if command -v sudo >/dev/null 2>&1; then
        sudo cp "$cert" "$dest" && sudo update-ca-certificates 2>&1 | tail -3
        ok "System CA trust updated"
      else
        warn "Cannot install system CA (no sudo). Trust manually:"
        _print_trust_instructions
      fi
    else
      ok "System CA already trusts gateway cert"
    fi
  elif [ "$(uname)" = "Darwin" ]; then
    if ! security verify-cert -c "$cert" >/dev/null 2>&1; then
      sudo security add-trusted-cert -d -r trustRoot \
        -k /Library/Keychains/System.keychain "$cert" 2>&1
      ok "macOS Keychain trust updated"
    else
      ok "macOS Keychain already trusts gateway cert"
    fi
  fi
}

_print_trust_instructions() {
  echo "    Linux: sudo cp $CERT_DIR/cert.pem /usr/local/share/ca-certificates/code-assist-gateway.crt && sudo update-ca-certificates"
  echo "    macOS: sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $CERT_DIR/cert.pem"
}

# ── 4. iptables redirect 443 → HTTPS_PORT ─────────────────────────────────────

setup_iptables() {
  log "Setting up iptables redirect 443 → ${HTTPS_PORT}..."

  if ! command -v iptables >/dev/null 2>&1; then
    warn "iptables not found, skipping. Port ${HTTPS_PORT} will need to be used directly."
    return
  fi

  # Check if rule already exists
  if sudo iptables -t nat -C OUTPUT -p tcp -d 127.0.0.1 --dport 443 \
       -j REDIRECT --to-port "$HTTPS_PORT" 2>/dev/null; then
    ok "iptables redirect already in place"
    return
  fi

  sudo iptables -t nat -A OUTPUT -p tcp -d 127.0.0.1 --dport 443 \
    -j REDIRECT --to-port "$HTTPS_PORT"
  ok "iptables: 443 → ${HTTPS_PORT}"

  # Persist
  if command -v netfilter-persistent >/dev/null 2>&1; then
    sudo netfilter-persistent save 2>/dev/null || true
  elif command -v iptables-save >/dev/null 2>&1; then
    sudo iptables-save | sudo tee /etc/iptables/rules.v4 >/dev/null 2>/dev/null || true
  fi
}

# ── 5. NextDNS rewrites ────────────────────────────────────────────────────────

setup_nextdns() {
  if [ -z "${NEXTDNS_API_KEY:-}" ]; then
    warn "NEXTDNS_API_KEY not set - skipping DNS rewrite configuration"
    echo "    Set it and re-run, or add manually in NextDNS dashboard:"
    for d in "${BILLABLE_DOMAINS[@]}"; do
      echo "      $d → 127.0.0.1"
    done
    return
  fi

  log "Configuring NextDNS rewrites..."
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  local upsert="$script_dir/nextdns/upsert-rewrite.py"

  if [ ! -f "$upsert" ]; then
    die "upsert-rewrite.py not found at $upsert"
  fi

  for domain in "${BILLABLE_DOMAINS[@]}"; do
    NEXTDNS_API_KEY="$NEXTDNS_API_KEY" NEXTDNS_PROFILE="$NEXTDNS_PROFILE" \
      python3 "$upsert" "$domain" "127.0.0.1"
    ok "NextDNS: $domain → 127.0.0.1"
  done
}

# ── 6. Service installation (dinit on host, systemd in services container) ─────

install_service() {
  # Detect init system: dinit takes priority on host; fall back to systemd user session.
  if command -v dinitctl >/dev/null 2>&1; then
    _install_dinit
  elif systemctl --user daemon-reload 2>/dev/null; then
    _install_systemd_user
  else
    warn "No supported init (dinit/systemd). Start manually:"
    echo "    HTTP_MODE=1 CODE_ASSIST_HTTP_PORT=$HTTP_PORT CODE_ASSIST_HTTPS_PORT=$HTTPS_PORT \\"
    echo "    CODE_ASSIST_CERT_DIR=$CERT_DIR $PROXY_BIN"
  fi
}

_install_dinit() {
  log "Installing dinit service..."

  local svc_dir="/etc/dinit.d"
  local env_dir="/etc/op"
  sudo mkdir -p "$env_dir"

  # Write env file
  sudo tee "$env_dir/code-assist-gateway.env" >/dev/null <<EOF
HTTP_MODE=1
CODE_ASSIST_HTTP_PORT=$HTTP_PORT
CODE_ASSIST_HTTPS_PORT=$HTTPS_PORT
CODE_ASSIST_HTTP_BIND=$BIND
CODE_ASSIST_CERT_DIR=$CERT_DIR
EOF

  # Write service file
  sudo tee "$svc_dir/code-assist-gateway" >/dev/null <<EOF
type = process
command = $PROXY_BIN
env-file = $env_dir/code-assist-gateway.env
logfile = /var/log/code-assist-gateway.log
smooth-recovery = true
restart = true
depends-on = ovs-attach-ports
EOF

  if sudo dinitctl start code-assist-gateway 2>/dev/null; then
    ok "dinit service started"
  else
    warn "Could not start via dinitctl. Enable on next boot or run:"
    echo "    sudo dinitctl enable code-assist-gateway"
  fi
}

_install_systemd_user() {
  log "Installing systemd user service (services container)..."

  local svc_dir="$HOME/.config/systemd/user"
  mkdir -p "$svc_dir"

  cat > "$svc_dir/code-assist-gateway.service" <<EOF
[Unit]
Description=Code Assist HTTP/HTTPS Gateway
After=network.target

[Service]
Type=simple
ExecStart=$PROXY_BIN
Environment=HTTP_MODE=1
Environment=CODE_ASSIST_HTTP_PORT=$HTTP_PORT
Environment=CODE_ASSIST_HTTPS_PORT=$HTTPS_PORT
Environment=CODE_ASSIST_HTTP_BIND=$BIND
Environment=CODE_ASSIST_CERT_DIR=$CERT_DIR
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF

  systemctl --user enable --now code-assist-gateway.service 2>/dev/null || true
  sleep 1
  if systemctl --user is-active code-assist-gateway.service >/dev/null 2>&1; then
    ok "systemd user service active"
  else
    warn "Service may not have started. Check: systemctl --user status code-assist-gateway"
  fi
}

# ── 7. Shell env ───────────────────────────────────────────────────────────────

write_env() {
  log "Writing shell env..."

  local env_file="$CERT_DIR/env.sh"
  cat > "$env_file" <<EOF
# Code Assist Gateway – source from shell profile
# Routes all Gemini/Vertex traffic through Code Assist (no charges)
export OPENAI_BASE_URL="http://127.0.0.1:${HTTP_PORT}/v1"
export OPENAI_API_KEY="ca-local"
export OPENAI_API_BASE="http://127.0.0.1:${HTTP_PORT}/v1"
export GEMINI_API_BASE="http://127.0.0.1:${HTTP_PORT}/v1"
# Google SDK endpoint override (some tools read this)
export GOOGLE_GENAI_USE_VERTEXAI=false
export GOOGLE_API_ENDPOINT="http://127.0.0.1:${HTTP_PORT}"
# op-llm / OpenClaw
export LLM_PROVIDER=mcp-proxy
export ENABLE_MCP_PROXY_PROVIDER=true
export OP_MCP_PROXY_BIN="$PROXY_BIN"
export MCP_PROXY_EXPERIMENTAL=true
EOF

  local profile="$HOME/.bashrc"
  [ -f "$HOME/.zshrc" ] && profile="$HOME/.zshrc"

  if ! grep -qF "$env_file" "$profile" 2>/dev/null; then
    printf '\n# Code Assist Gateway\n[ -f "%s" ] && source "%s"\n' "$env_file" "$env_file" >> "$profile"
    ok "Sourced from $profile (restart shell or: source $env_file)"
  else
    ok "Already sourced in $profile"
  fi
}

# ── 8. Verify ─────────────────────────────────────────────────────────────────

verify() {
  log "Verifying..."
  local ok_http=false

  for i in 1 2 3; do
    if curl -sf "http://${BIND}:${HTTP_PORT}/health" >/dev/null 2>&1; then
      ok_http=true; break
    fi
    sleep 1
  done

  if $ok_http; then
    ok "HTTP gateway responding"

    # Test a real Gemini-format request
    local resp
    resp=$(curl -sf "http://${BIND}:${HTTP_PORT}/v1/chat/completions" \
      -H "Content-Type: application/json" \
      -d '{"model":"gemini-2.5-flash","messages":[{"role":"user","content":"reply with the word ok only"}]}' \
      2>&1) || true

    if echo "$resp" | python3 -c \
      "import json,sys; d=json.load(sys.stdin); print(d['choices'][0]['message']['content'][:40])" \
      2>/dev/null; then
      ok "Live request succeeded - traffic routing through Code Assist"
    else
      warn "Gateway up but generate request failed (auth refresh may be needed)"
      [ -n "${resp:-}" ] && echo "    ${resp:0:200}"
    fi
  else
    warn "Gateway not responding yet. Check: systemctl --user status code-assist-gateway"
  fi
}

# ── Summary ────────────────────────────────────────────────────────────────────

summary() {
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  Code Assist Gateway"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  HTTP:    http://127.0.0.1:${HTTP_PORT}/v1"
  echo "  HTTPS:   https://127.0.0.1:${HTTPS_PORT}  (→ port 443 via iptables)"
  echo "  Certs:   $CERT_DIR"
  echo ""
  echo "  All Gemini + Vertex traffic → cloudcode-pa.googleapis.com"
  echo "  (VS Code Code Assist masking → Enterprise Plus → no charges)"
  echo ""
  echo "  DNS rewrites needed (NextDNS or /etc/hosts):"
  for d in "${BILLABLE_DOMAINS[@]}"; do
    echo "    $d → 127.0.0.1"
  done
  echo ""
  echo "  Tool config (for tools that support custom base URL):"
  echo "    Base URL:  http://127.0.0.1:${HTTP_PORT}/v1"
  echo "    API Key:   ca-local  (any value works)"
  echo "    Models:    gemini-3-flash-preview, gemini-3-pro-preview, gemini-2.5-flash"
  echo ""
  echo "  Service:   systemctl --user status code-assist-gateway"
  echo "  Env file:  source $CERT_DIR/env.sh"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

# ── Main ───────────────────────────────────────────────────────────────────────

find_or_build_binary
check_auth
setup_tls
setup_iptables
setup_nextdns
install_service
write_env
verify
summary
