//! Generate Rust types from a JSON Schema (draft 4) file.
//!
//! Wraps `schemafy_lib::Expander` directly (the library the `schemafy!`
//! macro itself calls) so generation is a plain function call instead of
//! the cargo-expand-and-extract dance a compile-time macro would otherwise
//! require: no build.rs, no throwaway `schemafy!()` binary, no `cargo
//! expand` step.
//!
//! Example:
//!   op-schema-codegen schemas/openflow/openflow15.json \
//!       --root Schema --output crates/op-plugins/src/state_plugins/openflow_generated.rs

use std::path::PathBuf;
use std::process::Command;

use anyhow::{Context, Result};
use clap::Parser;
use schemafy_lib::{Expander, Schema};

/// Generate Rust types from a JSON Schema (draft 4) file, without a macro or build.rs.
#[derive(Parser, Debug)]
#[command(name = "op-schema-codegen", version, about)]
struct Args {
    /// Path to the input JSON Schema file (draft 4).
    schema: PathBuf,

    /// Name of the schema's root type.
    #[arg(long, default_value = "Schema")]
    root: String,

    /// Rust path prefix used for schemafy_core support types (e.g. `TryFromPrimitive`).
    #[arg(long, default_value = "::schemafy_core::")]
    schemafy_path: String,

    /// Write generated code here instead of stdout.
    #[arg(long, short)]
    output: Option<PathBuf>,

    /// Skip running `rustfmt` on the output.
    #[arg(long)]
    no_format: bool,

    /// Enable OSCAL subid injection: lowercase-hyphenated `subject` segment
    /// of the taxonomy key (e.g. "incus", "netmaker"). When set, every
    /// generated struct/enum gets `#[derive(schemars::JsonSchema)]` plus a
    /// `sch.<component-type>.<subject>.<type>.schema@v1` subid, and every
    /// struct field gets `obs.<component-type>.<subject>.describe.<type>-<field>@v1`
    /// -- see subid-taxonomy.md / crates/op-blob/src/subid.rs for the format
    /// this mechanically satisfies.
    #[arg(long)]
    subid_subject: Option<String>,

    /// OSCAL component-type segment (position 2 of the taxonomy key).
    #[arg(long, default_value = "software")]
    subid_component_type: String,
}

/// Mirrors `op_blob::subid::COMPONENT_TYPES` -- kept as a literal copy since
/// op-schema-codegen is a standalone tool and shouldn't depend on op-blob.
const OSCAL_COMPONENT_TYPES: &[&str] = &[
    "service",
    "software",
    "network",
    "hardware",
    "data",
    "policy",
    "process",
    "plan",
    "guidance",
    "standard",
    "validation",
    "system",
    "interconnection",
];

fn main() -> Result<()> {
    let args = Args::parse();

    if let Some(subject) = &args.subid_subject {
        if !is_taxonomy_segment(subject) {
            anyhow::bail!("--subid-subject {subject:?}: must be lowercase-hyphenated [a-z0-9-]");
        }
        if !OSCAL_COMPONENT_TYPES.contains(&args.subid_component_type.as_str()) {
            anyhow::bail!(
                "--subid-component-type {:?}: not in OSCAL vocabulary {OSCAL_COMPONENT_TYPES:?}",
                args.subid_component_type
            );
        }
    }

    let raw = std::fs::read_to_string(&args.schema)
        .with_context(|| format!("reading schema file {}", args.schema.display()))?;
    let is_yaml = matches!(
        args.schema.extension().and_then(|e| e.to_str()),
        Some("yaml") | Some("yml")
    );
    let mut value: serde_json::Value = if is_yaml {
        serde_yaml::from_str(&raw)
            .with_context(|| format!("parsing {} as YAML JSON Schema (draft 4)", args.schema.display()))?
    } else {
        serde_json::from_str(&raw)
            .with_context(|| format!("parsing {} as JSON Schema (draft 4)", args.schema.display()))?
    };

    // schemafy_lib panics on non-string enum values (e.g. `enum: [0, 1, 2]`)
    // unless a sibling `enumNames` array is present -- draft-4 JSON Schema
    // permits numeric/bool enum values, so synthesize labels rather than
    // crash on real-world specs that use them.
    let synthesized = synthesize_enum_names(&mut value);
    if synthesized > 0 {
        eprintln!("op-schema-codegen: synthesized enumNames for {synthesized} non-string enum(s)");
    }

    let schema: Schema = serde_json::from_value(value)
        .with_context(|| format!("interpreting {} as JSON Schema (draft 4)", args.schema.display()))?;

    let mut expander = Expander::new(Some(args.root.as_str()), args.schemafy_path.as_str(), &schema);
    let code = expander.expand(&schema);
    let code = dedupe_top_level_items(code);
    let code = match &args.subid_subject {
        Some(subject) => inject_oscal_subids(code, subject, &args.subid_component_type)?,
        None => code,
    };

    let mut source = format!(
        "// AUTO-GENERATED by op-schema-codegen from {}.\n// DO NOT EDIT -- regenerate with:\n//   op-schema-codegen {} --root {} --output <path>\n\n#![allow(non_camel_case_types, non_snake_case)]\n\nuse serde::{{Deserialize, Serialize}};\n\n{}\n",
        args.schema.display(),
        args.schema.display(),
        args.root,
        code
    );

    match &args.output {
        Some(path) => {
            std::fs::write(path, &source)
                .with_context(|| format!("writing generated code to {}", path.display()))?;
            if !args.no_format {
                let status = Command::new("rustfmt").arg(path).status();
                if !matches!(status, Ok(s) if s.success()) {
                    eprintln!("op-schema-codegen: warning: rustfmt failed or is not installed; output left unformatted");
                }
            }
            // Run after rustfmt so real line breaks exist -- see
            // normalize_attr_spacing's doc comment.
            let formatted = std::fs::read_to_string(path)
                .with_context(|| format!("reading back {}", path.display()))?;
            std::fs::write(path, normalize_attr_spacing(&formatted))
                .with_context(|| format!("writing generated code to {}", path.display()))?;
            eprintln!("op-schema-codegen: wrote {}", path.display());
        }
        None => {
            if !args.no_format {
                source = rustfmt_str(&source).unwrap_or(source);
            }
            print!("{}", normalize_attr_spacing(&source));
        }
    }

    Ok(())
}

/// Recursively find `enum` arrays with non-string values and inject a
/// sibling `enumNames` array of synthesized labels, so schemafy_lib takes
/// the branch that actually supports numeric/bool values instead of
/// panicking. Returns the number of enums synthesized.
fn synthesize_enum_names(value: &mut serde_json::Value) -> usize {
    let mut count = 0;
    match value {
        serde_json::Value::Object(map) => {
            let needs_names = map
                .get("enum")
                .and_then(|e| e.as_array())
                .map(|values| {
                    !values.is_empty()
                        && values.iter().any(|v| !v.is_string())
                        && !map.contains_key("enumNames")
                })
                .unwrap_or(false);
            if needs_names {
                if let Some(values) = map.get("enum").and_then(|e| e.as_array()).cloned() {
                    let names: Vec<serde_json::Value> = values
                        .iter()
                        .map(|v| serde_json::Value::String(enum_label(v)))
                        .collect();
                    map.insert("enumNames".to_string(), serde_json::Value::Array(names));
                    count += 1;
                }
            }
            for v in map.values_mut() {
                count += synthesize_enum_names(v);
            }
        }
        serde_json::Value::Array(arr) => {
            for v in arr {
                count += synthesize_enum_names(v);
            }
        }
        _ => {}
    }
    count
}

fn enum_label(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::Number(n) if n.as_i64().map(|i| i < 0).unwrap_or(false) => {
            format!("Neg{}", n.as_i64().unwrap().unsigned_abs())
        }
        serde_json::Value::Number(n) => format!("Value{n}"),
        serde_json::Value::Bool(b) => if *b { "True" } else { "False" }.to_string(),
        serde_json::Value::Null => "Null".to_string(),
        other => other.to_string(),
    }
}

/// schemafy_lib accumulates generated items in an unordered, undeduplicated
/// Vec, so a definition reachable via two different $refs (or two source
/// names that collapse to the same PascalCase identifier) can emit two
/// conflicting top-level items with the same name. Keep the first
/// definition per identifier and drop later duplicates, warning to stderr.
fn dedupe_top_level_items(code: proc_macro2::TokenStream) -> proc_macro2::TokenStream {
    let file: syn::File = match syn::parse2(code.clone()) {
        Ok(f) => f,
        Err(_) => return code, // not parseable as a full file; leave as-is
    };

    let mut seen = std::collections::HashSet::new();
    let mut kept = Vec::new();
    for item in file.items {
        let name = item_ident(&item);
        match name {
            Some(name) if !seen.insert(name.clone()) => {
                eprintln!("op-schema-codegen: warning: dropping duplicate definition of `{name}`");
            }
            _ => kept.push(item),
        }
    }

    quote::quote! { #(#kept)* }
}

fn item_ident(item: &syn::Item) -> Option<String> {
    match item {
        syn::Item::Struct(s) => Some(s.ident.to_string()),
        syn::Item::Enum(e) => Some(e.ident.to_string()),
        syn::Item::Type(t) => Some(t.ident.to_string()),
        _ => None,
    }
}

/// Walk the generated file, add `#[derive(schemars::JsonSchema)]` to every
/// struct/enum that already derives `Serialize`/`Deserialize`, and inject a
/// taxonomy-conformant `x-oscal-subid` on the type and (for structs) each
/// named field. Every generated subid is checked with a local mirror of
/// `op_blob::subid::validate_subid` before being emitted -- a malformed one
/// aborts generation instead of shipping bad compliance metadata.
fn inject_oscal_subids(
    code: proc_macro2::TokenStream,
    subject: &str,
    component_type: &str,
) -> Result<proc_macro2::TokenStream> {
    let mut file: syn::File = syn::parse2(code)
        .map_err(|e| anyhow::anyhow!("generated code did not parse as a full file: {e}"))?;

    for item in &mut file.items {
        match item {
            syn::Item::Struct(s) => {
                add_json_schema_derive(&mut s.attrs);
                let type_slug = to_slug(&s.ident.to_string());
                add_subid_attr(&mut s.attrs, subid_for_type(component_type, subject, &type_slug)?);
                if let syn::Fields::Named(named) = &mut s.fields {
                    for field in &mut named.named {
                        let Some(ident) = &field.ident else { continue };
                        let field_slug = to_slug(&ident.to_string());
                        add_subid_attr(
                            &mut field.attrs,
                            subid_for_field(component_type, subject, &type_slug, &field_slug)?,
                        );
                    }
                }
            }
            syn::Item::Enum(e) => {
                add_json_schema_derive(&mut e.attrs);
                let type_slug = to_slug(&e.ident.to_string());
                add_subid_attr(&mut e.attrs, subid_for_type(component_type, subject, &type_slug)?);
            }
            _ => {}
        }
    }

    Ok(quote::quote! { #file })
}

fn subid_for_type(component_type: &str, subject: &str, type_slug: &str) -> Result<String> {
    let subid = format!("sch.{component_type}.{subject}.{type_slug}.schema@v1");
    validate_subid_local(&subid)?;
    Ok(subid)
}

fn subid_for_field(component_type: &str, subject: &str, type_slug: &str, field_slug: &str) -> Result<String> {
    let subid = format!("obs.{component_type}.{subject}.describe.{type_slug}-{field_slug}@v1");
    validate_subid_local(&subid)?;
    Ok(subid)
}

fn add_json_schema_derive(attrs: &mut [syn::Attribute]) {
    for attr in attrs.iter_mut() {
        if !attr.path().is_ident("derive") {
            continue;
        }
        let Ok(mut paths) = attr
            .parse_args_with(syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated)
        else {
            continue;
        };
        if paths.iter().any(|p| p.is_ident("JsonSchema")) {
            return;
        }
        paths.push(syn::parse_quote!(schemars::JsonSchema));
        *attr = syn::parse_quote!(#[derive(#paths)]);
        return;
    }
}

fn add_subid_attr(attrs: &mut Vec<syn::Attribute>, subid: String) {
    attrs.push(syn::parse_quote!(#[schemars(extend("x-oscal-subid" = #subid))]));
}

/// Local mirror of `op_blob::subid::validate_subid` -- kept as a literal
/// copy since op-schema-codegen is a standalone tool and shouldn't depend
/// on op-blob. See subid-taxonomy.md for the authoritative format.
fn validate_subid_local(subid: &str) -> Result<()> {
    const CATEGORIES: &[&str] = &["src", "prj", "sch", "mut", "obs", "evt", "exp"];

    let (base, version) = match subid.split_once('@') {
        Some((b, v)) => (b, Some(v)),
        None => (subid, None),
    };
    if let Some(v) = version {
        let ok = v.len() >= 2 && v.starts_with('v') && v[1..].chars().all(|c| c.is_ascii_digit());
        if !ok {
            anyhow::bail!("{subid}: version must be @vN, got @{v}");
        }
    }
    let segments: Vec<&str> = base.split('.').collect();
    if segments.len() < 4 || segments.len() > 5 {
        anyhow::bail!(
            "{subid}: expected category.component-type.subject.verb[.facet], got {} segments",
            segments.len()
        );
    }
    if !CATEGORIES.contains(&segments[0]) {
        anyhow::bail!("{subid}: category {:?} not one of {CATEGORIES:?}", segments[0]);
    }
    if !OSCAL_COMPONENT_TYPES.contains(&segments[1]) {
        anyhow::bail!("{subid}: component-type {:?} not in OSCAL vocabulary", segments[1]);
    }
    for seg in &segments[2..] {
        let ok = !seg.is_empty()
            && seg.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
            && !seg.starts_with('-')
            && !seg.ends_with('-');
        if !ok {
            anyhow::bail!("{subid}: segment {seg:?} must be lowercase hyphenated [a-z0-9-]");
        }
    }
    Ok(())
}

fn is_taxonomy_segment(s: &str) -> bool {
    !s.is_empty()
        && s.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
        && !s.starts_with('-')
        && !s.ends_with('-')
}

/// snake_case/PascalCase Rust identifier -> lowercase-hyphenated taxonomy segment.
fn to_slug(ident: &str) -> String {
    let mut out = String::new();
    for (i, c) in ident.chars().enumerate() {
        if c == '_' {
            out.push('-');
        } else if c.is_uppercase() {
            if i > 0 && !out.ends_with('-') {
                out.push('-');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out.trim_matches('-').to_string()
}

/// rustfmt leaves `# [schemars (extend (...))]`-shaped attributes exactly as
/// `proc_macro2::TokenStream`'s `Display` impl emits them (space between
/// every token) instead of collapsing them like `#[serde(...)]` -- verified
/// against a minimal hand-typed repro, not specific to this generator's
/// token reconstruction. Since we only ever emit attribute lines here,
/// collapse `# [` -> `#[`, `( ` -> `(`, ` )` -> `)`, and ` :: ` -> `::` on
/// lines whose trimmed form starts with `#`, leaving doc comments/string
/// content on other lines untouched.
fn normalize_attr_spacing(source: &str) -> String {
    source
        .lines()
        .map(|line| {
            let trimmed = line.trim_start();
            // Doc-comment attributes (`#[doc = "..."]`) already come out of
            // rustfmt correctly; only `schemars`/path-bearing attribute
            // lines have the spacing bug, so scope the rewrite tightly to
            // avoid ever touching prose inside a doc string.
            if !trimmed.starts_with('#') || !(trimmed.contains("schemars") || trimmed.contains("::")) {
                return line.to_string();
            }
            let indent = &line[..line.len() - trimmed.len()];
            let fixed = trimmed
                .replace("# [", "#[")
                .replace(" :: ", "::")
                .replace(" (", "(")
                .replace("( ", "(")
                .replace(" )", ")")
                .replace(" ,", ",");
            format!("{indent}{fixed}")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn rustfmt_str(source: &str) -> Option<String> {
    use std::io::Write;
    let mut child = Command::new("rustfmt")
        .arg("--emit=stdout")
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::null())
        .spawn()
        .ok()?;
    child.stdin.take()?.write_all(source.as_bytes()).ok()?;
    let output = child.wait_with_output().ok()?;
    if output.status.success() {
        String::from_utf8(output.stdout).ok()
    } else {
        None
    }
}
